// Code generated by ent, DO NOT EDIT.

package bundleplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldDescription, v))
}

// ProductName applies equality check predicate on the "product_name" field. It's identical to ProductNameEQ.
func ProductName(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldProductName, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldPrice, v))
}

// OriginalPrice applies equality check predicate on the "original_price" field. It's identical to OriginalPriceEQ.
func OriginalPrice(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldOriginalPrice, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldCurrency, v))
}

// ValidityDays applies equality check predicate on the "validity_days" field. It's identical to ValidityDaysEQ.
func ValidityDays(v int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityUnit applies equality check predicate on the "validity_unit" field. It's identical to ValidityUnitEQ.
func ValidityUnit(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldValidityUnit, v))
}

// SharedDailyLimitUsd applies equality check predicate on the "shared_daily_limit_usd" field. It's identical to SharedDailyLimitUsdEQ.
func SharedDailyLimitUsd(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldSharedDailyLimitUsd, v))
}

// SharedMonthlyLimitUsd applies equality check predicate on the "shared_monthly_limit_usd" field. It's identical to SharedMonthlyLimitUsdEQ.
func SharedMonthlyLimitUsd(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldSharedMonthlyLimitUsd, v))
}

// Features applies equality check predicate on the "features" field. It's identical to FeaturesEQ.
func Features(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldFeatures, v))
}

// ForSale applies equality check predicate on the "for_sale" field. It's identical to ForSaleEQ.
func ForSale(v bool) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldForSale, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldContainsFold(FieldDescription, v))
}

// ProductNameEQ applies the EQ predicate on the "product_name" field.
func ProductNameEQ(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldProductName, v))
}

// ProductNameNEQ applies the NEQ predicate on the "product_name" field.
func ProductNameNEQ(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldProductName, v))
}

// ProductNameIn applies the In predicate on the "product_name" field.
func ProductNameIn(vs ...string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldProductName, vs...))
}

// ProductNameNotIn applies the NotIn predicate on the "product_name" field.
func ProductNameNotIn(vs ...string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldProductName, vs...))
}

// ProductNameGT applies the GT predicate on the "product_name" field.
func ProductNameGT(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldProductName, v))
}

// ProductNameGTE applies the GTE predicate on the "product_name" field.
func ProductNameGTE(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldProductName, v))
}

// ProductNameLT applies the LT predicate on the "product_name" field.
func ProductNameLT(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldProductName, v))
}

// ProductNameLTE applies the LTE predicate on the "product_name" field.
func ProductNameLTE(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldProductName, v))
}

// ProductNameContains applies the Contains predicate on the "product_name" field.
func ProductNameContains(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldContains(FieldProductName, v))
}

// ProductNameHasPrefix applies the HasPrefix predicate on the "product_name" field.
func ProductNameHasPrefix(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldHasPrefix(FieldProductName, v))
}

// ProductNameHasSuffix applies the HasSuffix predicate on the "product_name" field.
func ProductNameHasSuffix(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldHasSuffix(FieldProductName, v))
}

// ProductNameEqualFold applies the EqualFold predicate on the "product_name" field.
func ProductNameEqualFold(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEqualFold(FieldProductName, v))
}

// ProductNameContainsFold applies the ContainsFold predicate on the "product_name" field.
func ProductNameContainsFold(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldContainsFold(FieldProductName, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldPrice, v))
}

// OriginalPriceEQ applies the EQ predicate on the "original_price" field.
func OriginalPriceEQ(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldOriginalPrice, v))
}

// OriginalPriceNEQ applies the NEQ predicate on the "original_price" field.
func OriginalPriceNEQ(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldOriginalPrice, v))
}

// OriginalPriceIn applies the In predicate on the "original_price" field.
func OriginalPriceIn(vs ...float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldOriginalPrice, vs...))
}

// OriginalPriceNotIn applies the NotIn predicate on the "original_price" field.
func OriginalPriceNotIn(vs ...float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldOriginalPrice, vs...))
}

// OriginalPriceGT applies the GT predicate on the "original_price" field.
func OriginalPriceGT(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldOriginalPrice, v))
}

// OriginalPriceGTE applies the GTE predicate on the "original_price" field.
func OriginalPriceGTE(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldOriginalPrice, v))
}

// OriginalPriceLT applies the LT predicate on the "original_price" field.
func OriginalPriceLT(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldOriginalPrice, v))
}

// OriginalPriceLTE applies the LTE predicate on the "original_price" field.
func OriginalPriceLTE(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldOriginalPrice, v))
}

// OriginalPriceIsNil applies the IsNil predicate on the "original_price" field.
func OriginalPriceIsNil() predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIsNull(FieldOriginalPrice))
}

// OriginalPriceNotNil applies the NotNil predicate on the "original_price" field.
func OriginalPriceNotNil() predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotNull(FieldOriginalPrice))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldContainsFold(FieldCurrency, v))
}

// ValidityDaysEQ applies the EQ predicate on the "validity_days" field.
func ValidityDaysEQ(v int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityDaysNEQ applies the NEQ predicate on the "validity_days" field.
func ValidityDaysNEQ(v int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldValidityDays, v))
}

// ValidityDaysIn applies the In predicate on the "validity_days" field.
func ValidityDaysIn(vs ...int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldValidityDays, vs...))
}

// ValidityDaysNotIn applies the NotIn predicate on the "validity_days" field.
func ValidityDaysNotIn(vs ...int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldValidityDays, vs...))
}

// ValidityDaysGT applies the GT predicate on the "validity_days" field.
func ValidityDaysGT(v int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldValidityDays, v))
}

// ValidityDaysGTE applies the GTE predicate on the "validity_days" field.
func ValidityDaysGTE(v int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldValidityDays, v))
}

// ValidityDaysLT applies the LT predicate on the "validity_days" field.
func ValidityDaysLT(v int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldValidityDays, v))
}

// ValidityDaysLTE applies the LTE predicate on the "validity_days" field.
func ValidityDaysLTE(v int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldValidityDays, v))
}

// ValidityUnitEQ applies the EQ predicate on the "validity_unit" field.
func ValidityUnitEQ(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldValidityUnit, v))
}

// ValidityUnitNEQ applies the NEQ predicate on the "validity_unit" field.
func ValidityUnitNEQ(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldValidityUnit, v))
}

// ValidityUnitIn applies the In predicate on the "validity_unit" field.
func ValidityUnitIn(vs ...string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldValidityUnit, vs...))
}

// ValidityUnitNotIn applies the NotIn predicate on the "validity_unit" field.
func ValidityUnitNotIn(vs ...string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldValidityUnit, vs...))
}

// ValidityUnitGT applies the GT predicate on the "validity_unit" field.
func ValidityUnitGT(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldValidityUnit, v))
}

// ValidityUnitGTE applies the GTE predicate on the "validity_unit" field.
func ValidityUnitGTE(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldValidityUnit, v))
}

// ValidityUnitLT applies the LT predicate on the "validity_unit" field.
func ValidityUnitLT(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldValidityUnit, v))
}

// ValidityUnitLTE applies the LTE predicate on the "validity_unit" field.
func ValidityUnitLTE(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldValidityUnit, v))
}

// ValidityUnitContains applies the Contains predicate on the "validity_unit" field.
func ValidityUnitContains(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldContains(FieldValidityUnit, v))
}

// ValidityUnitHasPrefix applies the HasPrefix predicate on the "validity_unit" field.
func ValidityUnitHasPrefix(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldHasPrefix(FieldValidityUnit, v))
}

// ValidityUnitHasSuffix applies the HasSuffix predicate on the "validity_unit" field.
func ValidityUnitHasSuffix(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldHasSuffix(FieldValidityUnit, v))
}

// ValidityUnitEqualFold applies the EqualFold predicate on the "validity_unit" field.
func ValidityUnitEqualFold(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEqualFold(FieldValidityUnit, v))
}

// ValidityUnitContainsFold applies the ContainsFold predicate on the "validity_unit" field.
func ValidityUnitContainsFold(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldContainsFold(FieldValidityUnit, v))
}

// SharedDailyLimitUsdEQ applies the EQ predicate on the "shared_daily_limit_usd" field.
func SharedDailyLimitUsdEQ(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldSharedDailyLimitUsd, v))
}

// SharedDailyLimitUsdNEQ applies the NEQ predicate on the "shared_daily_limit_usd" field.
func SharedDailyLimitUsdNEQ(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldSharedDailyLimitUsd, v))
}

// SharedDailyLimitUsdIn applies the In predicate on the "shared_daily_limit_usd" field.
func SharedDailyLimitUsdIn(vs ...float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldSharedDailyLimitUsd, vs...))
}

// SharedDailyLimitUsdNotIn applies the NotIn predicate on the "shared_daily_limit_usd" field.
func SharedDailyLimitUsdNotIn(vs ...float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldSharedDailyLimitUsd, vs...))
}

// SharedDailyLimitUsdGT applies the GT predicate on the "shared_daily_limit_usd" field.
func SharedDailyLimitUsdGT(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldSharedDailyLimitUsd, v))
}

// SharedDailyLimitUsdGTE applies the GTE predicate on the "shared_daily_limit_usd" field.
func SharedDailyLimitUsdGTE(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldSharedDailyLimitUsd, v))
}

// SharedDailyLimitUsdLT applies the LT predicate on the "shared_daily_limit_usd" field.
func SharedDailyLimitUsdLT(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldSharedDailyLimitUsd, v))
}

// SharedDailyLimitUsdLTE applies the LTE predicate on the "shared_daily_limit_usd" field.
func SharedDailyLimitUsdLTE(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldSharedDailyLimitUsd, v))
}

// SharedDailyLimitUsdIsNil applies the IsNil predicate on the "shared_daily_limit_usd" field.
func SharedDailyLimitUsdIsNil() predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIsNull(FieldSharedDailyLimitUsd))
}

// SharedDailyLimitUsdNotNil applies the NotNil predicate on the "shared_daily_limit_usd" field.
func SharedDailyLimitUsdNotNil() predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotNull(FieldSharedDailyLimitUsd))
}

// SharedMonthlyLimitUsdEQ applies the EQ predicate on the "shared_monthly_limit_usd" field.
func SharedMonthlyLimitUsdEQ(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldSharedMonthlyLimitUsd, v))
}

// SharedMonthlyLimitUsdNEQ applies the NEQ predicate on the "shared_monthly_limit_usd" field.
func SharedMonthlyLimitUsdNEQ(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldSharedMonthlyLimitUsd, v))
}

// SharedMonthlyLimitUsdIn applies the In predicate on the "shared_monthly_limit_usd" field.
func SharedMonthlyLimitUsdIn(vs ...float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldSharedMonthlyLimitUsd, vs...))
}

// SharedMonthlyLimitUsdNotIn applies the NotIn predicate on the "shared_monthly_limit_usd" field.
func SharedMonthlyLimitUsdNotIn(vs ...float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldSharedMonthlyLimitUsd, vs...))
}

// SharedMonthlyLimitUsdGT applies the GT predicate on the "shared_monthly_limit_usd" field.
func SharedMonthlyLimitUsdGT(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldSharedMonthlyLimitUsd, v))
}

// SharedMonthlyLimitUsdGTE applies the GTE predicate on the "shared_monthly_limit_usd" field.
func SharedMonthlyLimitUsdGTE(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldSharedMonthlyLimitUsd, v))
}

// SharedMonthlyLimitUsdLT applies the LT predicate on the "shared_monthly_limit_usd" field.
func SharedMonthlyLimitUsdLT(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldSharedMonthlyLimitUsd, v))
}

// SharedMonthlyLimitUsdLTE applies the LTE predicate on the "shared_monthly_limit_usd" field.
func SharedMonthlyLimitUsdLTE(v float64) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldSharedMonthlyLimitUsd, v))
}

// SharedMonthlyLimitUsdIsNil applies the IsNil predicate on the "shared_monthly_limit_usd" field.
func SharedMonthlyLimitUsdIsNil() predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIsNull(FieldSharedMonthlyLimitUsd))
}

// SharedMonthlyLimitUsdNotNil applies the NotNil predicate on the "shared_monthly_limit_usd" field.
func SharedMonthlyLimitUsdNotNil() predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotNull(FieldSharedMonthlyLimitUsd))
}

// FeaturesEQ applies the EQ predicate on the "features" field.
func FeaturesEQ(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldFeatures, v))
}

// FeaturesNEQ applies the NEQ predicate on the "features" field.
func FeaturesNEQ(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldFeatures, v))
}

// FeaturesIn applies the In predicate on the "features" field.
func FeaturesIn(vs ...string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldFeatures, vs...))
}

// FeaturesNotIn applies the NotIn predicate on the "features" field.
func FeaturesNotIn(vs ...string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldFeatures, vs...))
}

// FeaturesGT applies the GT predicate on the "features" field.
func FeaturesGT(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldFeatures, v))
}

// FeaturesGTE applies the GTE predicate on the "features" field.
func FeaturesGTE(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldFeatures, v))
}

// FeaturesLT applies the LT predicate on the "features" field.
func FeaturesLT(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldFeatures, v))
}

// FeaturesLTE applies the LTE predicate on the "features" field.
func FeaturesLTE(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldFeatures, v))
}

// FeaturesContains applies the Contains predicate on the "features" field.
func FeaturesContains(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldContains(FieldFeatures, v))
}

// FeaturesHasPrefix applies the HasPrefix predicate on the "features" field.
func FeaturesHasPrefix(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldHasPrefix(FieldFeatures, v))
}

// FeaturesHasSuffix applies the HasSuffix predicate on the "features" field.
func FeaturesHasSuffix(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldHasSuffix(FieldFeatures, v))
}

// FeaturesEqualFold applies the EqualFold predicate on the "features" field.
func FeaturesEqualFold(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEqualFold(FieldFeatures, v))
}

// FeaturesContainsFold applies the ContainsFold predicate on the "features" field.
func FeaturesContainsFold(v string) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldContainsFold(FieldFeatures, v))
}

// ForSaleEQ applies the EQ predicate on the "for_sale" field.
func ForSaleEQ(v bool) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldForSale, v))
}

// ForSaleNEQ applies the NEQ predicate on the "for_sale" field.
func ForSaleNEQ(v bool) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldForSale, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BundlePlan {
	return predicate.BundlePlan(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.BundlePlan {
	return predicate.BundlePlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.BundlePlanGroup) predicate.BundlePlan {
	return predicate.BundlePlan(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubscriptions applies the HasEdge predicate on the "subscriptions" edge.
func HasSubscriptions() predicate.BundlePlan {
	return predicate.BundlePlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubscriptionsTable, SubscriptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionsWith applies the HasEdge predicate on the "subscriptions" edge with a given conditions (other predicates).
func HasSubscriptionsWith(preds ...predicate.BundleSubscription) predicate.BundlePlan {
	return predicate.BundlePlan(func(s *sql.Selector) {
		step := newSubscriptionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BundlePlan) predicate.BundlePlan {
	return predicate.BundlePlan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BundlePlan) predicate.BundlePlan {
	return predicate.BundlePlan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BundlePlan) predicate.BundlePlan {
	return predicate.BundlePlan(sql.NotPredicates(p))
}
