// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bundleplan"
	"github.com/Wei-Shaw/sub2api/ent/bundleplangroup"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscription"
)

// BundlePlanCreate is the builder for creating a BundlePlan entity.
type BundlePlanCreate struct {
	config
	mutation *BundlePlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *BundlePlanCreate) SetName(v string) *BundlePlanCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *BundlePlanCreate) SetDescription(v string) *BundlePlanCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *BundlePlanCreate) SetNillableDescription(v *string) *BundlePlanCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetProductName sets the "product_name" field.
func (_c *BundlePlanCreate) SetProductName(v string) *BundlePlanCreate {
	_c.mutation.SetProductName(v)
	return _c
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_c *BundlePlanCreate) SetNillableProductName(v *string) *BundlePlanCreate {
	if v != nil {
		_c.SetProductName(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *BundlePlanCreate) SetPrice(v float64) *BundlePlanCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetOriginalPrice sets the "original_price" field.
func (_c *BundlePlanCreate) SetOriginalPrice(v float64) *BundlePlanCreate {
	_c.mutation.SetOriginalPrice(v)
	return _c
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_c *BundlePlanCreate) SetNillableOriginalPrice(v *float64) *BundlePlanCreate {
	if v != nil {
		_c.SetOriginalPrice(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *BundlePlanCreate) SetCurrency(v string) *BundlePlanCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *BundlePlanCreate) SetNillableCurrency(v *string) *BundlePlanCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *BundlePlanCreate) SetValidityDays(v int) *BundlePlanCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_c *BundlePlanCreate) SetNillableValidityDays(v *int) *BundlePlanCreate {
	if v != nil {
		_c.SetValidityDays(*v)
	}
	return _c
}

// SetValidityUnit sets the "validity_unit" field.
func (_c *BundlePlanCreate) SetValidityUnit(v string) *BundlePlanCreate {
	_c.mutation.SetValidityUnit(v)
	return _c
}

// SetNillableValidityUnit sets the "validity_unit" field if the given value is not nil.
func (_c *BundlePlanCreate) SetNillableValidityUnit(v *string) *BundlePlanCreate {
	if v != nil {
		_c.SetValidityUnit(*v)
	}
	return _c
}

// SetSharedDailyLimitUsd sets the "shared_daily_limit_usd" field.
func (_c *BundlePlanCreate) SetSharedDailyLimitUsd(v float64) *BundlePlanCreate {
	_c.mutation.SetSharedDailyLimitUsd(v)
	return _c
}

// SetNillableSharedDailyLimitUsd sets the "shared_daily_limit_usd" field if the given value is not nil.
func (_c *BundlePlanCreate) SetNillableSharedDailyLimitUsd(v *float64) *BundlePlanCreate {
	if v != nil {
		_c.SetSharedDailyLimitUsd(*v)
	}
	return _c
}

// SetSharedMonthlyLimitUsd sets the "shared_monthly_limit_usd" field.
func (_c *BundlePlanCreate) SetSharedMonthlyLimitUsd(v float64) *BundlePlanCreate {
	_c.mutation.SetSharedMonthlyLimitUsd(v)
	return _c
}

// SetNillableSharedMonthlyLimitUsd sets the "shared_monthly_limit_usd" field if the given value is not nil.
func (_c *BundlePlanCreate) SetNillableSharedMonthlyLimitUsd(v *float64) *BundlePlanCreate {
	if v != nil {
		_c.SetSharedMonthlyLimitUsd(*v)
	}
	return _c
}

// SetFeatures sets the "features" field.
func (_c *BundlePlanCreate) SetFeatures(v string) *BundlePlanCreate {
	_c.mutation.SetFeatures(v)
	return _c
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_c *BundlePlanCreate) SetNillableFeatures(v *string) *BundlePlanCreate {
	if v != nil {
		_c.SetFeatures(*v)
	}
	return _c
}

// SetForSale sets the "for_sale" field.
func (_c *BundlePlanCreate) SetForSale(v bool) *BundlePlanCreate {
	_c.mutation.SetForSale(v)
	return _c
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_c *BundlePlanCreate) SetNillableForSale(v *bool) *BundlePlanCreate {
	if v != nil {
		_c.SetForSale(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *BundlePlanCreate) SetSortOrder(v int) *BundlePlanCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *BundlePlanCreate) SetNillableSortOrder(v *int) *BundlePlanCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BundlePlanCreate) SetCreatedAt(v time.Time) *BundlePlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BundlePlanCreate) SetNillableCreatedAt(v *time.Time) *BundlePlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BundlePlanCreate) SetUpdatedAt(v time.Time) *BundlePlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BundlePlanCreate) SetNillableUpdatedAt(v *time.Time) *BundlePlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddGroupIDs adds the "groups" edge to the BundlePlanGroup entity by IDs.
func (_c *BundlePlanCreate) AddGroupIDs(ids ...int64) *BundlePlanCreate {
	_c.mutation.AddGroupIDs(ids...)
	return _c
}

// AddGroups adds the "groups" edges to the BundlePlanGroup entity.
func (_c *BundlePlanCreate) AddGroups(v ...*BundlePlanGroup) *BundlePlanCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGroupIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the BundleSubscription entity by IDs.
func (_c *BundlePlanCreate) AddSubscriptionIDs(ids ...int64) *BundlePlanCreate {
	_c.mutation.AddSubscriptionIDs(ids...)
	return _c
}

// AddSubscriptions adds the "subscriptions" edges to the BundleSubscription entity.
func (_c *BundlePlanCreate) AddSubscriptions(v ...*BundleSubscription) *BundlePlanCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubscriptionIDs(ids...)
}

// Mutation returns the BundlePlanMutation object of the builder.
func (_c *BundlePlanCreate) Mutation() *BundlePlanMutation {
	return _c.mutation
}

// Save creates the BundlePlan in the database.
func (_c *BundlePlanCreate) Save(ctx context.Context) (*BundlePlan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BundlePlanCreate) SaveX(ctx context.Context) *BundlePlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BundlePlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BundlePlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BundlePlanCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := bundleplan.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.ProductName(); !ok {
		v := bundleplan.DefaultProductName
		_c.mutation.SetProductName(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := bundleplan.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		v := bundleplan.DefaultValidityDays
		_c.mutation.SetValidityDays(v)
	}
	if _, ok := _c.mutation.ValidityUnit(); !ok {
		v := bundleplan.DefaultValidityUnit
		_c.mutation.SetValidityUnit(v)
	}
	if _, ok := _c.mutation.Features(); !ok {
		v := bundleplan.DefaultFeatures
		_c.mutation.SetFeatures(v)
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		v := bundleplan.DefaultForSale
		_c.mutation.SetForSale(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := bundleplan.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := bundleplan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := bundleplan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BundlePlanCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "BundlePlan.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := bundleplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BundlePlan.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "BundlePlan.description"`)}
	}
	if _, ok := _c.mutation.ProductName(); !ok {
		return &ValidationError{Name: "product_name", err: errors.New(`ent: missing required field "BundlePlan.product_name"`)}
	}
	if v, ok := _c.mutation.ProductName(); ok {
		if err := bundleplan.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "BundlePlan.product_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "BundlePlan.price"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "BundlePlan.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := bundleplan.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "BundlePlan.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		return &ValidationError{Name: "validity_days", err: errors.New(`ent: missing required field "BundlePlan.validity_days"`)}
	}
	if _, ok := _c.mutation.ValidityUnit(); !ok {
		return &ValidationError{Name: "validity_unit", err: errors.New(`ent: missing required field "BundlePlan.validity_unit"`)}
	}
	if v, ok := _c.mutation.ValidityUnit(); ok {
		if err := bundleplan.ValidityUnitValidator(v); err != nil {
			return &ValidationError{Name: "validity_unit", err: fmt.Errorf(`ent: validator failed for field "BundlePlan.validity_unit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Features(); !ok {
		return &ValidationError{Name: "features", err: errors.New(`ent: missing required field "BundlePlan.features"`)}
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		return &ValidationError{Name: "for_sale", err: errors.New(`ent: missing required field "BundlePlan.for_sale"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "BundlePlan.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BundlePlan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BundlePlan.updated_at"`)}
	}
	return nil
}

func (_c *BundlePlanCreate) sqlSave(ctx context.Context) (*BundlePlan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BundlePlanCreate) createSpec() (*BundlePlan, *sqlgraph.CreateSpec) {
	var (
		_node = &BundlePlan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bundleplan.Table, sqlgraph.NewFieldSpec(bundleplan.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(bundleplan.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(bundleplan.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.ProductName(); ok {
		_spec.SetField(bundleplan.FieldProductName, field.TypeString, value)
		_node.ProductName = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(bundleplan.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.OriginalPrice(); ok {
		_spec.SetField(bundleplan.FieldOriginalPrice, field.TypeFloat64, value)
		_node.OriginalPrice = &value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(bundleplan.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(bundleplan.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = value
	}
	if value, ok := _c.mutation.ValidityUnit(); ok {
		_spec.SetField(bundleplan.FieldValidityUnit, field.TypeString, value)
		_node.ValidityUnit = value
	}
	if value, ok := _c.mutation.SharedDailyLimitUsd(); ok {
		_spec.SetField(bundleplan.FieldSharedDailyLimitUsd, field.TypeFloat64, value)
		_node.SharedDailyLimitUsd = &value
	}
	if value, ok := _c.mutation.SharedMonthlyLimitUsd(); ok {
		_spec.SetField(bundleplan.FieldSharedMonthlyLimitUsd, field.TypeFloat64, value)
		_node.SharedMonthlyLimitUsd = &value
	}
	if value, ok := _c.mutation.Features(); ok {
		_spec.SetField(bundleplan.FieldFeatures, field.TypeString, value)
		_node.Features = value
	}
	if value, ok := _c.mutation.ForSale(); ok {
		_spec.SetField(bundleplan.FieldForSale, field.TypeBool, value)
		_node.ForSale = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(bundleplan.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(bundleplan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(bundleplan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleplan.GroupsTable,
			Columns: []string{bundleplan.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplangroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleplan.SubscriptionsTable,
			Columns: []string{bundleplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BundlePlan.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BundlePlanUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *BundlePlanCreate) OnConflict(opts ...sql.ConflictOption) *BundlePlanUpsertOne {
	_c.conflict = opts
	return &BundlePlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BundlePlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BundlePlanCreate) OnConflictColumns(columns ...string) *BundlePlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BundlePlanUpsertOne{
		create: _c,
	}
}

type (
	// BundlePlanUpsertOne is the builder for "upsert"-ing
	//  one BundlePlan node.
	BundlePlanUpsertOne struct {
		create *BundlePlanCreate
	}

	// BundlePlanUpsert is the "OnConflict" setter.
	BundlePlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *BundlePlanUpsert) SetName(v string) *BundlePlanUpsert {
	u.Set(bundleplan.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BundlePlanUpsert) UpdateName() *BundlePlanUpsert {
	u.SetExcluded(bundleplan.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *BundlePlanUpsert) SetDescription(v string) *BundlePlanUpsert {
	u.Set(bundleplan.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BundlePlanUpsert) UpdateDescription() *BundlePlanUpsert {
	u.SetExcluded(bundleplan.FieldDescription)
	return u
}

// SetProductName sets the "product_name" field.
func (u *BundlePlanUpsert) SetProductName(v string) *BundlePlanUpsert {
	u.Set(bundleplan.FieldProductName, v)
	return u
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *BundlePlanUpsert) UpdateProductName() *BundlePlanUpsert {
	u.SetExcluded(bundleplan.FieldProductName)
	return u
}

// SetPrice sets the "price" field.
func (u *BundlePlanUpsert) SetPrice(v float64) *BundlePlanUpsert {
	u.Set(bundleplan.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *BundlePlanUpsert) UpdatePrice() *BundlePlanUpsert {
	u.SetExcluded(bundleplan.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *BundlePlanUpsert) AddPrice(v float64) *BundlePlanUpsert {
	u.Add(bundleplan.FieldPrice, v)
	return u
}

// SetOriginalPrice sets the "original_price" field.
func (u *BundlePlanUpsert) SetOriginalPrice(v float64) *BundlePlanUpsert {
	u.Set(bundleplan.FieldOriginalPrice, v)
	return u
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *BundlePlanUpsert) UpdateOriginalPrice() *BundlePlanUpsert {
	u.SetExcluded(bundleplan.FieldOriginalPrice)
	return u
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *BundlePlanUpsert) AddOriginalPrice(v float64) *BundlePlanUpsert {
	u.Add(bundleplan.FieldOriginalPrice, v)
	return u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *BundlePlanUpsert) ClearOriginalPrice() *BundlePlanUpsert {
	u.SetNull(bundleplan.FieldOriginalPrice)
	return u
}

// SetCurrency sets the "currency" field.
func (u *BundlePlanUpsert) SetCurrency(v string) *BundlePlanUpsert {
	u.Set(bundleplan.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BundlePlanUpsert) UpdateCurrency() *BundlePlanUpsert {
	u.SetExcluded(bundleplan.FieldCurrency)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *BundlePlanUpsert) SetValidityDays(v int) *BundlePlanUpsert {
	u.Set(bundleplan.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *BundlePlanUpsert) UpdateValidityDays() *BundlePlanUpsert {
	u.SetExcluded(bundleplan.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *BundlePlanUpsert) AddValidityDays(v int) *BundlePlanUpsert {
	u.Add(bundleplan.FieldValidityDays, v)
	return u
}

// SetValidityUnit sets the "validity_unit" field.
func (u *BundlePlanUpsert) SetValidityUnit(v string) *BundlePlanUpsert {
	u.Set(bundleplan.FieldValidityUnit, v)
	return u
}

// UpdateValidityUnit sets the "validity_unit" field to the value that was provided on create.
func (u *BundlePlanUpsert) UpdateValidityUnit() *BundlePlanUpsert {
	u.SetExcluded(bundleplan.FieldValidityUnit)
	return u
}

// SetSharedDailyLimitUsd sets the "shared_daily_limit_usd" field.
func (u *BundlePlanUpsert) SetSharedDailyLimitUsd(v float64) *BundlePlanUpsert {
	u.Set(bundleplan.FieldSharedDailyLimitUsd, v)
	return u
}

// UpdateSharedDailyLimitUsd sets the "shared_daily_limit_usd" field to the value that was provided on create.
func (u *BundlePlanUpsert) UpdateSharedDailyLimitUsd() *BundlePlanUpsert {
	u.SetExcluded(bundleplan.FieldSharedDailyLimitUsd)
	return u
}

// AddSharedDailyLimitUsd adds v to the "shared_daily_limit_usd" field.
func (u *BundlePlanUpsert) AddSharedDailyLimitUsd(v float64) *BundlePlanUpsert {
	u.Add(bundleplan.FieldSharedDailyLimitUsd, v)
	return u
}

// ClearSharedDailyLimitUsd clears the value of the "shared_daily_limit_usd" field.
func (u *BundlePlanUpsert) ClearSharedDailyLimitUsd() *BundlePlanUpsert {
	u.SetNull(bundleplan.FieldSharedDailyLimitUsd)
	return u
}

// SetSharedMonthlyLimitUsd sets the "shared_monthly_limit_usd" field.
func (u *BundlePlanUpsert) SetSharedMonthlyLimitUsd(v float64) *BundlePlanUpsert {
	u.Set(bundleplan.FieldSharedMonthlyLimitUsd, v)
	return u
}

// UpdateSharedMonthlyLimitUsd sets the "shared_monthly_limit_usd" field to the value that was provided on create.
func (u *BundlePlanUpsert) UpdateSharedMonthlyLimitUsd() *BundlePlanUpsert {
	u.SetExcluded(bundleplan.FieldSharedMonthlyLimitUsd)
	return u
}

// AddSharedMonthlyLimitUsd adds v to the "shared_monthly_limit_usd" field.
func (u *BundlePlanUpsert) AddSharedMonthlyLimitUsd(v float64) *BundlePlanUpsert {
	u.Add(bundleplan.FieldSharedMonthlyLimitUsd, v)
	return u
}

// ClearSharedMonthlyLimitUsd clears the value of the "shared_monthly_limit_usd" field.
func (u *BundlePlanUpsert) ClearSharedMonthlyLimitUsd() *BundlePlanUpsert {
	u.SetNull(bundleplan.FieldSharedMonthlyLimitUsd)
	return u
}

// SetFeatures sets the "features" field.
func (u *BundlePlanUpsert) SetFeatures(v string) *BundlePlanUpsert {
	u.Set(bundleplan.FieldFeatures, v)
	return u
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *BundlePlanUpsert) UpdateFeatures() *BundlePlanUpsert {
	u.SetExcluded(bundleplan.FieldFeatures)
	return u
}

// SetForSale sets the "for_sale" field.
func (u *BundlePlanUpsert) SetForSale(v bool) *BundlePlanUpsert {
	u.Set(bundleplan.FieldForSale, v)
	return u
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *BundlePlanUpsert) UpdateForSale() *BundlePlanUpsert {
	u.SetExcluded(bundleplan.FieldForSale)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *BundlePlanUpsert) SetSortOrder(v int) *BundlePlanUpsert {
	u.Set(bundleplan.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BundlePlanUpsert) UpdateSortOrder() *BundlePlanUpsert {
	u.SetExcluded(bundleplan.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BundlePlanUpsert) AddSortOrder(v int) *BundlePlanUpsert {
	u.Add(bundleplan.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BundlePlanUpsert) SetUpdatedAt(v time.Time) *BundlePlanUpsert {
	u.Set(bundleplan.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BundlePlanUpsert) UpdateUpdatedAt() *BundlePlanUpsert {
	u.SetExcluded(bundleplan.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BundlePlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BundlePlanUpsertOne) UpdateNewValues() *BundlePlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(bundleplan.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BundlePlan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BundlePlanUpsertOne) Ignore() *BundlePlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BundlePlanUpsertOne) DoNothing() *BundlePlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BundlePlanCreate.OnConflict
// documentation for more info.
func (u *BundlePlanUpsertOne) Update(set func(*BundlePlanUpsert)) *BundlePlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BundlePlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *BundlePlanUpsertOne) SetName(v string) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BundlePlanUpsertOne) UpdateName() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *BundlePlanUpsertOne) SetDescription(v string) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BundlePlanUpsertOne) UpdateDescription() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateDescription()
	})
}

// SetProductName sets the "product_name" field.
func (u *BundlePlanUpsertOne) SetProductName(v string) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetProductName(v)
	})
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *BundlePlanUpsertOne) UpdateProductName() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateProductName()
	})
}

// SetPrice sets the "price" field.
func (u *BundlePlanUpsertOne) SetPrice(v float64) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *BundlePlanUpsertOne) AddPrice(v float64) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *BundlePlanUpsertOne) UpdatePrice() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdatePrice()
	})
}

// SetOriginalPrice sets the "original_price" field.
func (u *BundlePlanUpsertOne) SetOriginalPrice(v float64) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetOriginalPrice(v)
	})
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *BundlePlanUpsertOne) AddOriginalPrice(v float64) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.AddOriginalPrice(v)
	})
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *BundlePlanUpsertOne) UpdateOriginalPrice() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateOriginalPrice()
	})
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *BundlePlanUpsertOne) ClearOriginalPrice() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.ClearOriginalPrice()
	})
}

// SetCurrency sets the "currency" field.
func (u *BundlePlanUpsertOne) SetCurrency(v string) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BundlePlanUpsertOne) UpdateCurrency() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateCurrency()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *BundlePlanUpsertOne) SetValidityDays(v int) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *BundlePlanUpsertOne) AddValidityDays(v int) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *BundlePlanUpsertOne) UpdateValidityDays() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateValidityDays()
	})
}

// SetValidityUnit sets the "validity_unit" field.
func (u *BundlePlanUpsertOne) SetValidityUnit(v string) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetValidityUnit(v)
	})
}

// UpdateValidityUnit sets the "validity_unit" field to the value that was provided on create.
func (u *BundlePlanUpsertOne) UpdateValidityUnit() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateValidityUnit()
	})
}

// SetSharedDailyLimitUsd sets the "shared_daily_limit_usd" field.
func (u *BundlePlanUpsertOne) SetSharedDailyLimitUsd(v float64) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetSharedDailyLimitUsd(v)
	})
}

// AddSharedDailyLimitUsd adds v to the "shared_daily_limit_usd" field.
func (u *BundlePlanUpsertOne) AddSharedDailyLimitUsd(v float64) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.AddSharedDailyLimitUsd(v)
	})
}

// UpdateSharedDailyLimitUsd sets the "shared_daily_limit_usd" field to the value that was provided on create.
func (u *BundlePlanUpsertOne) UpdateSharedDailyLimitUsd() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateSharedDailyLimitUsd()
	})
}

// ClearSharedDailyLimitUsd clears the value of the "shared_daily_limit_usd" field.
func (u *BundlePlanUpsertOne) ClearSharedDailyLimitUsd() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.ClearSharedDailyLimitUsd()
	})
}

// SetSharedMonthlyLimitUsd sets the "shared_monthly_limit_usd" field.
func (u *BundlePlanUpsertOne) SetSharedMonthlyLimitUsd(v float64) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetSharedMonthlyLimitUsd(v)
	})
}

// AddSharedMonthlyLimitUsd adds v to the "shared_monthly_limit_usd" field.
func (u *BundlePlanUpsertOne) AddSharedMonthlyLimitUsd(v float64) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.AddSharedMonthlyLimitUsd(v)
	})
}

// UpdateSharedMonthlyLimitUsd sets the "shared_monthly_limit_usd" field to the value that was provided on create.
func (u *BundlePlanUpsertOne) UpdateSharedMonthlyLimitUsd() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateSharedMonthlyLimitUsd()
	})
}

// ClearSharedMonthlyLimitUsd clears the value of the "shared_monthly_limit_usd" field.
func (u *BundlePlanUpsertOne) ClearSharedMonthlyLimitUsd() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.ClearSharedMonthlyLimitUsd()
	})
}

// SetFeatures sets the "features" field.
func (u *BundlePlanUpsertOne) SetFeatures(v string) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *BundlePlanUpsertOne) UpdateFeatures() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateFeatures()
	})
}

// SetForSale sets the "for_sale" field.
func (u *BundlePlanUpsertOne) SetForSale(v bool) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *BundlePlanUpsertOne) UpdateForSale() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateForSale()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *BundlePlanUpsertOne) SetSortOrder(v int) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BundlePlanUpsertOne) AddSortOrder(v int) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BundlePlanUpsertOne) UpdateSortOrder() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BundlePlanUpsertOne) SetUpdatedAt(v time.Time) *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BundlePlanUpsertOne) UpdateUpdatedAt() *BundlePlanUpsertOne {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BundlePlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BundlePlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BundlePlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BundlePlanUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BundlePlanUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BundlePlanCreateBulk is the builder for creating many BundlePlan entities in bulk.
type BundlePlanCreateBulk struct {
	config
	err      error
	builders []*BundlePlanCreate
	conflict []sql.ConflictOption
}

// Save creates the BundlePlan entities in the database.
func (_c *BundlePlanCreateBulk) Save(ctx context.Context) ([]*BundlePlan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BundlePlan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BundlePlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BundlePlanCreateBulk) SaveX(ctx context.Context) []*BundlePlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BundlePlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BundlePlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BundlePlan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BundlePlanUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *BundlePlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *BundlePlanUpsertBulk {
	_c.conflict = opts
	return &BundlePlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BundlePlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BundlePlanCreateBulk) OnConflictColumns(columns ...string) *BundlePlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BundlePlanUpsertBulk{
		create: _c,
	}
}

// BundlePlanUpsertBulk is the builder for "upsert"-ing
// a bulk of BundlePlan nodes.
type BundlePlanUpsertBulk struct {
	create *BundlePlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BundlePlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BundlePlanUpsertBulk) UpdateNewValues() *BundlePlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(bundleplan.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BundlePlan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BundlePlanUpsertBulk) Ignore() *BundlePlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BundlePlanUpsertBulk) DoNothing() *BundlePlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BundlePlanCreateBulk.OnConflict
// documentation for more info.
func (u *BundlePlanUpsertBulk) Update(set func(*BundlePlanUpsert)) *BundlePlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BundlePlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *BundlePlanUpsertBulk) SetName(v string) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BundlePlanUpsertBulk) UpdateName() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *BundlePlanUpsertBulk) SetDescription(v string) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BundlePlanUpsertBulk) UpdateDescription() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateDescription()
	})
}

// SetProductName sets the "product_name" field.
func (u *BundlePlanUpsertBulk) SetProductName(v string) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetProductName(v)
	})
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *BundlePlanUpsertBulk) UpdateProductName() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateProductName()
	})
}

// SetPrice sets the "price" field.
func (u *BundlePlanUpsertBulk) SetPrice(v float64) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *BundlePlanUpsertBulk) AddPrice(v float64) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *BundlePlanUpsertBulk) UpdatePrice() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdatePrice()
	})
}

// SetOriginalPrice sets the "original_price" field.
func (u *BundlePlanUpsertBulk) SetOriginalPrice(v float64) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetOriginalPrice(v)
	})
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *BundlePlanUpsertBulk) AddOriginalPrice(v float64) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.AddOriginalPrice(v)
	})
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *BundlePlanUpsertBulk) UpdateOriginalPrice() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateOriginalPrice()
	})
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *BundlePlanUpsertBulk) ClearOriginalPrice() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.ClearOriginalPrice()
	})
}

// SetCurrency sets the "currency" field.
func (u *BundlePlanUpsertBulk) SetCurrency(v string) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BundlePlanUpsertBulk) UpdateCurrency() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateCurrency()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *BundlePlanUpsertBulk) SetValidityDays(v int) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *BundlePlanUpsertBulk) AddValidityDays(v int) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *BundlePlanUpsertBulk) UpdateValidityDays() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateValidityDays()
	})
}

// SetValidityUnit sets the "validity_unit" field.
func (u *BundlePlanUpsertBulk) SetValidityUnit(v string) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetValidityUnit(v)
	})
}

// UpdateValidityUnit sets the "validity_unit" field to the value that was provided on create.
func (u *BundlePlanUpsertBulk) UpdateValidityUnit() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateValidityUnit()
	})
}

// SetSharedDailyLimitUsd sets the "shared_daily_limit_usd" field.
func (u *BundlePlanUpsertBulk) SetSharedDailyLimitUsd(v float64) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetSharedDailyLimitUsd(v)
	})
}

// AddSharedDailyLimitUsd adds v to the "shared_daily_limit_usd" field.
func (u *BundlePlanUpsertBulk) AddSharedDailyLimitUsd(v float64) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.AddSharedDailyLimitUsd(v)
	})
}

// UpdateSharedDailyLimitUsd sets the "shared_daily_limit_usd" field to the value that was provided on create.
func (u *BundlePlanUpsertBulk) UpdateSharedDailyLimitUsd() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateSharedDailyLimitUsd()
	})
}

// ClearSharedDailyLimitUsd clears the value of the "shared_daily_limit_usd" field.
func (u *BundlePlanUpsertBulk) ClearSharedDailyLimitUsd() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.ClearSharedDailyLimitUsd()
	})
}

// SetSharedMonthlyLimitUsd sets the "shared_monthly_limit_usd" field.
func (u *BundlePlanUpsertBulk) SetSharedMonthlyLimitUsd(v float64) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetSharedMonthlyLimitUsd(v)
	})
}

// AddSharedMonthlyLimitUsd adds v to the "shared_monthly_limit_usd" field.
func (u *BundlePlanUpsertBulk) AddSharedMonthlyLimitUsd(v float64) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.AddSharedMonthlyLimitUsd(v)
	})
}

// UpdateSharedMonthlyLimitUsd sets the "shared_monthly_limit_usd" field to the value that was provided on create.
func (u *BundlePlanUpsertBulk) UpdateSharedMonthlyLimitUsd() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateSharedMonthlyLimitUsd()
	})
}

// ClearSharedMonthlyLimitUsd clears the value of the "shared_monthly_limit_usd" field.
func (u *BundlePlanUpsertBulk) ClearSharedMonthlyLimitUsd() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.ClearSharedMonthlyLimitUsd()
	})
}

// SetFeatures sets the "features" field.
func (u *BundlePlanUpsertBulk) SetFeatures(v string) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *BundlePlanUpsertBulk) UpdateFeatures() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateFeatures()
	})
}

// SetForSale sets the "for_sale" field.
func (u *BundlePlanUpsertBulk) SetForSale(v bool) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *BundlePlanUpsertBulk) UpdateForSale() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateForSale()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *BundlePlanUpsertBulk) SetSortOrder(v int) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BundlePlanUpsertBulk) AddSortOrder(v int) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BundlePlanUpsertBulk) UpdateSortOrder() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BundlePlanUpsertBulk) SetUpdatedAt(v time.Time) *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BundlePlanUpsertBulk) UpdateUpdatedAt() *BundlePlanUpsertBulk {
	return u.Update(func(s *BundlePlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BundlePlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BundlePlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BundlePlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BundlePlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
