// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/bundleplan"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscription"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// BundleSubscription is the model entity for the BundleSubscription schema.
type BundleSubscription struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// BundlePlanID holds the value of the "bundle_plan_id" field.
	BundlePlanID int64 `json:"bundle_plan_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// DailyWindowStart holds the value of the "daily_window_start" field.
	DailyWindowStart *time.Time `json:"daily_window_start,omitempty"`
	// MonthlyWindowStart holds the value of the "monthly_window_start" field.
	MonthlyWindowStart *time.Time `json:"monthly_window_start,omitempty"`
	// DailyUsageUsd holds the value of the "daily_usage_usd" field.
	DailyUsageUsd float64 `json:"daily_usage_usd,omitempty"`
	// MonthlyUsageUsd holds the value of the "monthly_usage_usd" field.
	MonthlyUsageUsd float64 `json:"monthly_usage_usd,omitempty"`
	// PaymentOrderID holds the value of the "payment_order_id" field.
	PaymentOrderID *int64 `json:"payment_order_id,omitempty"`
	// AssignedBy holds the value of the "assigned_by" field.
	AssignedBy *int64 `json:"assigned_by,omitempty"`
	// AssignedAt holds the value of the "assigned_at" field.
	AssignedAt time.Time `json:"assigned_at,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BundleSubscriptionQuery when eager-loading is set.
	Edges        BundleSubscriptionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BundleSubscriptionEdges holds the relations/edges for other nodes in the graph.
type BundleSubscriptionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Plan holds the value of the plan edge.
	Plan *BundlePlan `json:"plan,omitempty"`
	// Entitlements holds the value of the entitlements edge.
	Entitlements []*BundleSubscriptionEntitlement `json:"entitlements,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BundleSubscriptionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BundleSubscriptionEdges) PlanOrErr() (*BundlePlan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: bundleplan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// EntitlementsOrErr returns the Entitlements value or an error if the edge
// was not loaded in eager-loading.
func (e BundleSubscriptionEdges) EntitlementsOrErr() ([]*BundleSubscriptionEntitlement, error) {
	if e.loadedTypes[2] {
		return e.Entitlements, nil
	}
	return nil, &NotLoadedError{edge: "entitlements"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BundleSubscription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bundlesubscription.FieldDailyUsageUsd, bundlesubscription.FieldMonthlyUsageUsd:
			values[i] = new(sql.NullFloat64)
		case bundlesubscription.FieldID, bundlesubscription.FieldUserID, bundlesubscription.FieldBundlePlanID, bundlesubscription.FieldPaymentOrderID, bundlesubscription.FieldAssignedBy:
			values[i] = new(sql.NullInt64)
		case bundlesubscription.FieldStatus, bundlesubscription.FieldNotes:
			values[i] = new(sql.NullString)
		case bundlesubscription.FieldStartsAt, bundlesubscription.FieldExpiresAt, bundlesubscription.FieldDailyWindowStart, bundlesubscription.FieldMonthlyWindowStart, bundlesubscription.FieldAssignedAt, bundlesubscription.FieldCreatedAt, bundlesubscription.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BundleSubscription fields.
func (_m *BundleSubscription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bundlesubscription.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case bundlesubscription.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case bundlesubscription.FieldBundlePlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bundle_plan_id", values[i])
			} else if value.Valid {
				_m.BundlePlanID = value.Int64
			}
		case bundlesubscription.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case bundlesubscription.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case bundlesubscription.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case bundlesubscription.FieldDailyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field daily_window_start", values[i])
			} else if value.Valid {
				_m.DailyWindowStart = new(time.Time)
				*_m.DailyWindowStart = value.Time
			}
		case bundlesubscription.FieldMonthlyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_window_start", values[i])
			} else if value.Valid {
				_m.MonthlyWindowStart = new(time.Time)
				*_m.MonthlyWindowStart = value.Time
			}
		case bundlesubscription.FieldDailyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_usage_usd", values[i])
			} else if value.Valid {
				_m.DailyUsageUsd = value.Float64
			}
		case bundlesubscription.FieldMonthlyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_usage_usd", values[i])
			} else if value.Valid {
				_m.MonthlyUsageUsd = value.Float64
			}
		case bundlesubscription.FieldPaymentOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_id", values[i])
			} else if value.Valid {
				_m.PaymentOrderID = new(int64)
				*_m.PaymentOrderID = value.Int64
			}
		case bundlesubscription.FieldAssignedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_by", values[i])
			} else if value.Valid {
				_m.AssignedBy = new(int64)
				*_m.AssignedBy = value.Int64
			}
		case bundlesubscription.FieldAssignedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_at", values[i])
			} else if value.Valid {
				_m.AssignedAt = value.Time
			}
		case bundlesubscription.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case bundlesubscription.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case bundlesubscription.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BundleSubscription.
// This includes values selected through modifiers, order, etc.
func (_m *BundleSubscription) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the BundleSubscription entity.
func (_m *BundleSubscription) QueryUser() *UserQuery {
	return NewBundleSubscriptionClient(_m.config).QueryUser(_m)
}

// QueryPlan queries the "plan" edge of the BundleSubscription entity.
func (_m *BundleSubscription) QueryPlan() *BundlePlanQuery {
	return NewBundleSubscriptionClient(_m.config).QueryPlan(_m)
}

// QueryEntitlements queries the "entitlements" edge of the BundleSubscription entity.
func (_m *BundleSubscription) QueryEntitlements() *BundleSubscriptionEntitlementQuery {
	return NewBundleSubscriptionClient(_m.config).QueryEntitlements(_m)
}

// Update returns a builder for updating this BundleSubscription.
// Note that you need to call BundleSubscription.Unwrap() before calling this method if this BundleSubscription
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BundleSubscription) Update() *BundleSubscriptionUpdateOne {
	return NewBundleSubscriptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BundleSubscription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BundleSubscription) Unwrap() *BundleSubscription {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BundleSubscription is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BundleSubscription) String() string {
	var builder strings.Builder
	builder.WriteString("BundleSubscription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("bundle_plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BundlePlanID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DailyWindowStart; v != nil {
		builder.WriteString("daily_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.MonthlyWindowStart; v != nil {
		builder.WriteString("monthly_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("daily_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("monthly_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyUsageUsd))
	builder.WriteString(", ")
	if v := _m.PaymentOrderID; v != nil {
		builder.WriteString("payment_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AssignedBy; v != nil {
		builder.WriteString("assigned_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("assigned_at=")
	builder.WriteString(_m.AssignedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BundleSubscriptions is a parsable slice of BundleSubscription.
type BundleSubscriptions []*BundleSubscription
