// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscription"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscriptionentitlement"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// BundleSubscriptionEntitlementCreate is the builder for creating a BundleSubscriptionEntitlement entity.
type BundleSubscriptionEntitlementCreate struct {
	config
	mutation *BundleSubscriptionEntitlementMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBundleSubscriptionID sets the "bundle_subscription_id" field.
func (_c *BundleSubscriptionEntitlementCreate) SetBundleSubscriptionID(v int64) *BundleSubscriptionEntitlementCreate {
	_c.mutation.SetBundleSubscriptionID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *BundleSubscriptionEntitlementCreate) SetGroupID(v int64) *BundleSubscriptionEntitlementCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *BundleSubscriptionEntitlementCreate) SetPlatform(v string) *BundleSubscriptionEntitlementCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_c *BundleSubscriptionEntitlementCreate) SetDailyLimitUsd(v float64) *BundleSubscriptionEntitlementCreate {
	_c.mutation.SetDailyLimitUsd(v)
	return _c
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_c *BundleSubscriptionEntitlementCreate) SetNillableDailyLimitUsd(v *float64) *BundleSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetDailyLimitUsd(*v)
	}
	return _c
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_c *BundleSubscriptionEntitlementCreate) SetMonthlyLimitUsd(v float64) *BundleSubscriptionEntitlementCreate {
	_c.mutation.SetMonthlyLimitUsd(v)
	return _c
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_c *BundleSubscriptionEntitlementCreate) SetNillableMonthlyLimitUsd(v *float64) *BundleSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetMonthlyLimitUsd(*v)
	}
	return _c
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_c *BundleSubscriptionEntitlementCreate) SetDailyUsageUsd(v float64) *BundleSubscriptionEntitlementCreate {
	_c.mutation.SetDailyUsageUsd(v)
	return _c
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_c *BundleSubscriptionEntitlementCreate) SetNillableDailyUsageUsd(v *float64) *BundleSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetDailyUsageUsd(*v)
	}
	return _c
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_c *BundleSubscriptionEntitlementCreate) SetMonthlyUsageUsd(v float64) *BundleSubscriptionEntitlementCreate {
	_c.mutation.SetMonthlyUsageUsd(v)
	return _c
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_c *BundleSubscriptionEntitlementCreate) SetNillableMonthlyUsageUsd(v *float64) *BundleSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetMonthlyUsageUsd(*v)
	}
	return _c
}

// SetSubscriptionID sets the "subscription" edge to the BundleSubscription entity by ID.
func (_c *BundleSubscriptionEntitlementCreate) SetSubscriptionID(id int64) *BundleSubscriptionEntitlementCreate {
	_c.mutation.SetSubscriptionID(id)
	return _c
}

// SetSubscription sets the "subscription" edge to the BundleSubscription entity.
func (_c *BundleSubscriptionEntitlementCreate) SetSubscription(v *BundleSubscription) *BundleSubscriptionEntitlementCreate {
	return _c.SetSubscriptionID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *BundleSubscriptionEntitlementCreate) SetGroup(v *Group) *BundleSubscriptionEntitlementCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the BundleSubscriptionEntitlementMutation object of the builder.
func (_c *BundleSubscriptionEntitlementCreate) Mutation() *BundleSubscriptionEntitlementMutation {
	return _c.mutation
}

// Save creates the BundleSubscriptionEntitlement in the database.
func (_c *BundleSubscriptionEntitlementCreate) Save(ctx context.Context) (*BundleSubscriptionEntitlement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BundleSubscriptionEntitlementCreate) SaveX(ctx context.Context) *BundleSubscriptionEntitlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BundleSubscriptionEntitlementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BundleSubscriptionEntitlementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BundleSubscriptionEntitlementCreate) defaults() {
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		v := bundlesubscriptionentitlement.DefaultDailyUsageUsd
		_c.mutation.SetDailyUsageUsd(v)
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		v := bundlesubscriptionentitlement.DefaultMonthlyUsageUsd
		_c.mutation.SetMonthlyUsageUsd(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BundleSubscriptionEntitlementCreate) check() error {
	if _, ok := _c.mutation.BundleSubscriptionID(); !ok {
		return &ValidationError{Name: "bundle_subscription_id", err: errors.New(`ent: missing required field "BundleSubscriptionEntitlement.bundle_subscription_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "BundleSubscriptionEntitlement.group_id"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "BundleSubscriptionEntitlement.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := bundlesubscriptionentitlement.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "BundleSubscriptionEntitlement.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		return &ValidationError{Name: "daily_usage_usd", err: errors.New(`ent: missing required field "BundleSubscriptionEntitlement.daily_usage_usd"`)}
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		return &ValidationError{Name: "monthly_usage_usd", err: errors.New(`ent: missing required field "BundleSubscriptionEntitlement.monthly_usage_usd"`)}
	}
	if len(_c.mutation.SubscriptionIDs()) == 0 {
		return &ValidationError{Name: "subscription", err: errors.New(`ent: missing required edge "BundleSubscriptionEntitlement.subscription"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "BundleSubscriptionEntitlement.group"`)}
	}
	return nil
}

func (_c *BundleSubscriptionEntitlementCreate) sqlSave(ctx context.Context) (*BundleSubscriptionEntitlement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BundleSubscriptionEntitlementCreate) createSpec() (*BundleSubscriptionEntitlement, *sqlgraph.CreateSpec) {
	var (
		_node = &BundleSubscriptionEntitlement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bundlesubscriptionentitlement.Table, sqlgraph.NewFieldSpec(bundlesubscriptionentitlement.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.DailyLimitUsd(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldDailyLimitUsd, field.TypeFloat64, value)
		_node.DailyLimitUsd = &value
	}
	if value, ok := _c.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldMonthlyLimitUsd, field.TypeFloat64, value)
		_node.MonthlyLimitUsd = &value
	}
	if value, ok := _c.mutation.DailyUsageUsd(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldDailyUsageUsd, field.TypeFloat64, value)
		_node.DailyUsageUsd = value
	}
	if value, ok := _c.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldMonthlyUsageUsd, field.TypeFloat64, value)
		_node.MonthlyUsageUsd = value
	}
	if nodes := _c.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscriptionentitlement.SubscriptionTable,
			Columns: []string{bundlesubscriptionentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BundleSubscriptionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscriptionentitlement.GroupTable,
			Columns: []string{bundlesubscriptionentitlement.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BundleSubscriptionEntitlement.Create().
//		SetBundleSubscriptionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BundleSubscriptionEntitlementUpsert) {
//			SetBundleSubscriptionID(v+v).
//		}).
//		Exec(ctx)
func (_c *BundleSubscriptionEntitlementCreate) OnConflict(opts ...sql.ConflictOption) *BundleSubscriptionEntitlementUpsertOne {
	_c.conflict = opts
	return &BundleSubscriptionEntitlementUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BundleSubscriptionEntitlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BundleSubscriptionEntitlementCreate) OnConflictColumns(columns ...string) *BundleSubscriptionEntitlementUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BundleSubscriptionEntitlementUpsertOne{
		create: _c,
	}
}

type (
	// BundleSubscriptionEntitlementUpsertOne is the builder for "upsert"-ing
	//  one BundleSubscriptionEntitlement node.
	BundleSubscriptionEntitlementUpsertOne struct {
		create *BundleSubscriptionEntitlementCreate
	}

	// BundleSubscriptionEntitlementUpsert is the "OnConflict" setter.
	BundleSubscriptionEntitlementUpsert struct {
		*sql.UpdateSet
	}
)

// SetBundleSubscriptionID sets the "bundle_subscription_id" field.
func (u *BundleSubscriptionEntitlementUpsert) SetBundleSubscriptionID(v int64) *BundleSubscriptionEntitlementUpsert {
	u.Set(bundlesubscriptionentitlement.FieldBundleSubscriptionID, v)
	return u
}

// UpdateBundleSubscriptionID sets the "bundle_subscription_id" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsert) UpdateBundleSubscriptionID() *BundleSubscriptionEntitlementUpsert {
	u.SetExcluded(bundlesubscriptionentitlement.FieldBundleSubscriptionID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *BundleSubscriptionEntitlementUpsert) SetGroupID(v int64) *BundleSubscriptionEntitlementUpsert {
	u.Set(bundlesubscriptionentitlement.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsert) UpdateGroupID() *BundleSubscriptionEntitlementUpsert {
	u.SetExcluded(bundlesubscriptionentitlement.FieldGroupID)
	return u
}

// SetPlatform sets the "platform" field.
func (u *BundleSubscriptionEntitlementUpsert) SetPlatform(v string) *BundleSubscriptionEntitlementUpsert {
	u.Set(bundlesubscriptionentitlement.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsert) UpdatePlatform() *BundleSubscriptionEntitlementUpsert {
	u.SetExcluded(bundlesubscriptionentitlement.FieldPlatform)
	return u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsert) SetDailyLimitUsd(v float64) *BundleSubscriptionEntitlementUpsert {
	u.Set(bundlesubscriptionentitlement.FieldDailyLimitUsd, v)
	return u
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsert) UpdateDailyLimitUsd() *BundleSubscriptionEntitlementUpsert {
	u.SetExcluded(bundlesubscriptionentitlement.FieldDailyLimitUsd)
	return u
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsert) AddDailyLimitUsd(v float64) *BundleSubscriptionEntitlementUpsert {
	u.Add(bundlesubscriptionentitlement.FieldDailyLimitUsd, v)
	return u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsert) ClearDailyLimitUsd() *BundleSubscriptionEntitlementUpsert {
	u.SetNull(bundlesubscriptionentitlement.FieldDailyLimitUsd)
	return u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsert) SetMonthlyLimitUsd(v float64) *BundleSubscriptionEntitlementUpsert {
	u.Set(bundlesubscriptionentitlement.FieldMonthlyLimitUsd, v)
	return u
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsert) UpdateMonthlyLimitUsd() *BundleSubscriptionEntitlementUpsert {
	u.SetExcluded(bundlesubscriptionentitlement.FieldMonthlyLimitUsd)
	return u
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsert) AddMonthlyLimitUsd(v float64) *BundleSubscriptionEntitlementUpsert {
	u.Add(bundlesubscriptionentitlement.FieldMonthlyLimitUsd, v)
	return u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsert) ClearMonthlyLimitUsd() *BundleSubscriptionEntitlementUpsert {
	u.SetNull(bundlesubscriptionentitlement.FieldMonthlyLimitUsd)
	return u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *BundleSubscriptionEntitlementUpsert) SetDailyUsageUsd(v float64) *BundleSubscriptionEntitlementUpsert {
	u.Set(bundlesubscriptionentitlement.FieldDailyUsageUsd, v)
	return u
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsert) UpdateDailyUsageUsd() *BundleSubscriptionEntitlementUpsert {
	u.SetExcluded(bundlesubscriptionentitlement.FieldDailyUsageUsd)
	return u
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *BundleSubscriptionEntitlementUpsert) AddDailyUsageUsd(v float64) *BundleSubscriptionEntitlementUpsert {
	u.Add(bundlesubscriptionentitlement.FieldDailyUsageUsd, v)
	return u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *BundleSubscriptionEntitlementUpsert) SetMonthlyUsageUsd(v float64) *BundleSubscriptionEntitlementUpsert {
	u.Set(bundlesubscriptionentitlement.FieldMonthlyUsageUsd, v)
	return u
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsert) UpdateMonthlyUsageUsd() *BundleSubscriptionEntitlementUpsert {
	u.SetExcluded(bundlesubscriptionentitlement.FieldMonthlyUsageUsd)
	return u
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *BundleSubscriptionEntitlementUpsert) AddMonthlyUsageUsd(v float64) *BundleSubscriptionEntitlementUpsert {
	u.Add(bundlesubscriptionentitlement.FieldMonthlyUsageUsd, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BundleSubscriptionEntitlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BundleSubscriptionEntitlementUpsertOne) UpdateNewValues() *BundleSubscriptionEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BundleSubscriptionEntitlement.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BundleSubscriptionEntitlementUpsertOne) Ignore() *BundleSubscriptionEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BundleSubscriptionEntitlementUpsertOne) DoNothing() *BundleSubscriptionEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BundleSubscriptionEntitlementCreate.OnConflict
// documentation for more info.
func (u *BundleSubscriptionEntitlementUpsertOne) Update(set func(*BundleSubscriptionEntitlementUpsert)) *BundleSubscriptionEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BundleSubscriptionEntitlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetBundleSubscriptionID sets the "bundle_subscription_id" field.
func (u *BundleSubscriptionEntitlementUpsertOne) SetBundleSubscriptionID(v int64) *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.SetBundleSubscriptionID(v)
	})
}

// UpdateBundleSubscriptionID sets the "bundle_subscription_id" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsertOne) UpdateBundleSubscriptionID() *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.UpdateBundleSubscriptionID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *BundleSubscriptionEntitlementUpsertOne) SetGroupID(v int64) *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsertOne) UpdateGroupID() *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.UpdateGroupID()
	})
}

// SetPlatform sets the "platform" field.
func (u *BundleSubscriptionEntitlementUpsertOne) SetPlatform(v string) *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsertOne) UpdatePlatform() *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.UpdatePlatform()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsertOne) SetDailyLimitUsd(v float64) *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsertOne) AddDailyLimitUsd(v float64) *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsertOne) UpdateDailyLimitUsd() *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsertOne) ClearDailyLimitUsd() *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.ClearDailyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsertOne) SetMonthlyLimitUsd(v float64) *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsertOne) AddMonthlyLimitUsd(v float64) *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsertOne) UpdateMonthlyLimitUsd() *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsertOne) ClearMonthlyLimitUsd() *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.ClearMonthlyLimitUsd()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *BundleSubscriptionEntitlementUpsertOne) SetDailyUsageUsd(v float64) *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *BundleSubscriptionEntitlementUpsertOne) AddDailyUsageUsd(v float64) *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsertOne) UpdateDailyUsageUsd() *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *BundleSubscriptionEntitlementUpsertOne) SetMonthlyUsageUsd(v float64) *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *BundleSubscriptionEntitlementUpsertOne) AddMonthlyUsageUsd(v float64) *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsertOne) UpdateMonthlyUsageUsd() *BundleSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// Exec executes the query.
func (u *BundleSubscriptionEntitlementUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BundleSubscriptionEntitlementCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BundleSubscriptionEntitlementUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BundleSubscriptionEntitlementUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BundleSubscriptionEntitlementUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BundleSubscriptionEntitlementCreateBulk is the builder for creating many BundleSubscriptionEntitlement entities in bulk.
type BundleSubscriptionEntitlementCreateBulk struct {
	config
	err      error
	builders []*BundleSubscriptionEntitlementCreate
	conflict []sql.ConflictOption
}

// Save creates the BundleSubscriptionEntitlement entities in the database.
func (_c *BundleSubscriptionEntitlementCreateBulk) Save(ctx context.Context) ([]*BundleSubscriptionEntitlement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BundleSubscriptionEntitlement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BundleSubscriptionEntitlementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BundleSubscriptionEntitlementCreateBulk) SaveX(ctx context.Context) []*BundleSubscriptionEntitlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BundleSubscriptionEntitlementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BundleSubscriptionEntitlementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BundleSubscriptionEntitlement.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BundleSubscriptionEntitlementUpsert) {
//			SetBundleSubscriptionID(v+v).
//		}).
//		Exec(ctx)
func (_c *BundleSubscriptionEntitlementCreateBulk) OnConflict(opts ...sql.ConflictOption) *BundleSubscriptionEntitlementUpsertBulk {
	_c.conflict = opts
	return &BundleSubscriptionEntitlementUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BundleSubscriptionEntitlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BundleSubscriptionEntitlementCreateBulk) OnConflictColumns(columns ...string) *BundleSubscriptionEntitlementUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BundleSubscriptionEntitlementUpsertBulk{
		create: _c,
	}
}

// BundleSubscriptionEntitlementUpsertBulk is the builder for "upsert"-ing
// a bulk of BundleSubscriptionEntitlement nodes.
type BundleSubscriptionEntitlementUpsertBulk struct {
	create *BundleSubscriptionEntitlementCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BundleSubscriptionEntitlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BundleSubscriptionEntitlementUpsertBulk) UpdateNewValues() *BundleSubscriptionEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BundleSubscriptionEntitlement.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BundleSubscriptionEntitlementUpsertBulk) Ignore() *BundleSubscriptionEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BundleSubscriptionEntitlementUpsertBulk) DoNothing() *BundleSubscriptionEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BundleSubscriptionEntitlementCreateBulk.OnConflict
// documentation for more info.
func (u *BundleSubscriptionEntitlementUpsertBulk) Update(set func(*BundleSubscriptionEntitlementUpsert)) *BundleSubscriptionEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BundleSubscriptionEntitlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetBundleSubscriptionID sets the "bundle_subscription_id" field.
func (u *BundleSubscriptionEntitlementUpsertBulk) SetBundleSubscriptionID(v int64) *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.SetBundleSubscriptionID(v)
	})
}

// UpdateBundleSubscriptionID sets the "bundle_subscription_id" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsertBulk) UpdateBundleSubscriptionID() *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.UpdateBundleSubscriptionID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *BundleSubscriptionEntitlementUpsertBulk) SetGroupID(v int64) *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsertBulk) UpdateGroupID() *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.UpdateGroupID()
	})
}

// SetPlatform sets the "platform" field.
func (u *BundleSubscriptionEntitlementUpsertBulk) SetPlatform(v string) *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsertBulk) UpdatePlatform() *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.UpdatePlatform()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsertBulk) SetDailyLimitUsd(v float64) *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsertBulk) AddDailyLimitUsd(v float64) *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsertBulk) UpdateDailyLimitUsd() *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsertBulk) ClearDailyLimitUsd() *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.ClearDailyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsertBulk) SetMonthlyLimitUsd(v float64) *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsertBulk) AddMonthlyLimitUsd(v float64) *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsertBulk) UpdateMonthlyLimitUsd() *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *BundleSubscriptionEntitlementUpsertBulk) ClearMonthlyLimitUsd() *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.ClearMonthlyLimitUsd()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *BundleSubscriptionEntitlementUpsertBulk) SetDailyUsageUsd(v float64) *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *BundleSubscriptionEntitlementUpsertBulk) AddDailyUsageUsd(v float64) *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsertBulk) UpdateDailyUsageUsd() *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *BundleSubscriptionEntitlementUpsertBulk) SetMonthlyUsageUsd(v float64) *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *BundleSubscriptionEntitlementUpsertBulk) AddMonthlyUsageUsd(v float64) *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *BundleSubscriptionEntitlementUpsertBulk) UpdateMonthlyUsageUsd() *BundleSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *BundleSubscriptionEntitlementUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// Exec executes the query.
func (u *BundleSubscriptionEntitlementUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BundleSubscriptionEntitlementCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BundleSubscriptionEntitlementCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BundleSubscriptionEntitlementUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
