// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscription"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscriptionentitlement"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BundleSubscriptionEntitlementUpdate is the builder for updating BundleSubscriptionEntitlement entities.
type BundleSubscriptionEntitlementUpdate struct {
	config
	hooks    []Hook
	mutation *BundleSubscriptionEntitlementMutation
}

// Where appends a list predicates to the BundleSubscriptionEntitlementUpdate builder.
func (_u *BundleSubscriptionEntitlementUpdate) Where(ps ...predicate.BundleSubscriptionEntitlement) *BundleSubscriptionEntitlementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBundleSubscriptionID sets the "bundle_subscription_id" field.
func (_u *BundleSubscriptionEntitlementUpdate) SetBundleSubscriptionID(v int64) *BundleSubscriptionEntitlementUpdate {
	_u.mutation.SetBundleSubscriptionID(v)
	return _u
}

// SetNillableBundleSubscriptionID sets the "bundle_subscription_id" field if the given value is not nil.
func (_u *BundleSubscriptionEntitlementUpdate) SetNillableBundleSubscriptionID(v *int64) *BundleSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetBundleSubscriptionID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *BundleSubscriptionEntitlementUpdate) SetGroupID(v int64) *BundleSubscriptionEntitlementUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *BundleSubscriptionEntitlementUpdate) SetNillableGroupID(v *int64) *BundleSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *BundleSubscriptionEntitlementUpdate) SetPlatform(v string) *BundleSubscriptionEntitlementUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *BundleSubscriptionEntitlementUpdate) SetNillablePlatform(v *string) *BundleSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *BundleSubscriptionEntitlementUpdate) SetDailyLimitUsd(v float64) *BundleSubscriptionEntitlementUpdate {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *BundleSubscriptionEntitlementUpdate) SetNillableDailyLimitUsd(v *float64) *BundleSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *BundleSubscriptionEntitlementUpdate) AddDailyLimitUsd(v float64) *BundleSubscriptionEntitlementUpdate {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (_u *BundleSubscriptionEntitlementUpdate) ClearDailyLimitUsd() *BundleSubscriptionEntitlementUpdate {
	_u.mutation.ClearDailyLimitUsd()
	return _u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_u *BundleSubscriptionEntitlementUpdate) SetMonthlyLimitUsd(v float64) *BundleSubscriptionEntitlementUpdate {
	_u.mutation.ResetMonthlyLimitUsd()
	_u.mutation.SetMonthlyLimitUsd(v)
	return _u
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_u *BundleSubscriptionEntitlementUpdate) SetNillableMonthlyLimitUsd(v *float64) *BundleSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetMonthlyLimitUsd(*v)
	}
	return _u
}

// AddMonthlyLimitUsd adds value to the "monthly_limit_usd" field.
func (_u *BundleSubscriptionEntitlementUpdate) AddMonthlyLimitUsd(v float64) *BundleSubscriptionEntitlementUpdate {
	_u.mutation.AddMonthlyLimitUsd(v)
	return _u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (_u *BundleSubscriptionEntitlementUpdate) ClearMonthlyLimitUsd() *BundleSubscriptionEntitlementUpdate {
	_u.mutation.ClearMonthlyLimitUsd()
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *BundleSubscriptionEntitlementUpdate) SetDailyUsageUsd(v float64) *BundleSubscriptionEntitlementUpdate {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *BundleSubscriptionEntitlementUpdate) SetNillableDailyUsageUsd(v *float64) *BundleSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *BundleSubscriptionEntitlementUpdate) AddDailyUsageUsd(v float64) *BundleSubscriptionEntitlementUpdate {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *BundleSubscriptionEntitlementUpdate) SetMonthlyUsageUsd(v float64) *BundleSubscriptionEntitlementUpdate {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *BundleSubscriptionEntitlementUpdate) SetNillableMonthlyUsageUsd(v *float64) *BundleSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *BundleSubscriptionEntitlementUpdate) AddMonthlyUsageUsd(v float64) *BundleSubscriptionEntitlementUpdate {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetSubscriptionID sets the "subscription" edge to the BundleSubscription entity by ID.
func (_u *BundleSubscriptionEntitlementUpdate) SetSubscriptionID(id int64) *BundleSubscriptionEntitlementUpdate {
	_u.mutation.SetSubscriptionID(id)
	return _u
}

// SetSubscription sets the "subscription" edge to the BundleSubscription entity.
func (_u *BundleSubscriptionEntitlementUpdate) SetSubscription(v *BundleSubscription) *BundleSubscriptionEntitlementUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *BundleSubscriptionEntitlementUpdate) SetGroup(v *Group) *BundleSubscriptionEntitlementUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the BundleSubscriptionEntitlementMutation object of the builder.
func (_u *BundleSubscriptionEntitlementUpdate) Mutation() *BundleSubscriptionEntitlementMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the BundleSubscription entity.
func (_u *BundleSubscriptionEntitlementUpdate) ClearSubscription() *BundleSubscriptionEntitlementUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *BundleSubscriptionEntitlementUpdate) ClearGroup() *BundleSubscriptionEntitlementUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BundleSubscriptionEntitlementUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundleSubscriptionEntitlementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BundleSubscriptionEntitlementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundleSubscriptionEntitlementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BundleSubscriptionEntitlementUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := bundlesubscriptionentitlement.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "BundleSubscriptionEntitlement.platform": %w`, err)}
		}
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleSubscriptionEntitlement.subscription"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleSubscriptionEntitlement.group"`)
	}
	return nil
}

func (_u *BundleSubscriptionEntitlementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundlesubscriptionentitlement.Table, bundlesubscriptionentitlement.Columns, sqlgraph.NewFieldSpec(bundlesubscriptionentitlement.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(bundlesubscriptionentitlement.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.DailyLimitUsdCleared() {
		_spec.ClearField(bundlesubscriptionentitlement.FieldDailyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsd(); ok {
		_spec.AddField(bundlesubscriptionentitlement.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyLimitUsdCleared() {
		_spec.ClearField(bundlesubscriptionentitlement.FieldMonthlyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(bundlesubscriptionentitlement.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(bundlesubscriptionentitlement.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscriptionentitlement.SubscriptionTable,
			Columns: []string{bundlesubscriptionentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscriptionentitlement.SubscriptionTable,
			Columns: []string{bundlesubscriptionentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscriptionentitlement.GroupTable,
			Columns: []string{bundlesubscriptionentitlement.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscriptionentitlement.GroupTable,
			Columns: []string{bundlesubscriptionentitlement.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundlesubscriptionentitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BundleSubscriptionEntitlementUpdateOne is the builder for updating a single BundleSubscriptionEntitlement entity.
type BundleSubscriptionEntitlementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BundleSubscriptionEntitlementMutation
}

// SetBundleSubscriptionID sets the "bundle_subscription_id" field.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetBundleSubscriptionID(v int64) *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.SetBundleSubscriptionID(v)
	return _u
}

// SetNillableBundleSubscriptionID sets the "bundle_subscription_id" field if the given value is not nil.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetNillableBundleSubscriptionID(v *int64) *BundleSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetBundleSubscriptionID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetGroupID(v int64) *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetNillableGroupID(v *int64) *BundleSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetPlatform(v string) *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetNillablePlatform(v *string) *BundleSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetDailyLimitUsd(v float64) *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetNillableDailyLimitUsd(v *float64) *BundleSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *BundleSubscriptionEntitlementUpdateOne) AddDailyLimitUsd(v float64) *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (_u *BundleSubscriptionEntitlementUpdateOne) ClearDailyLimitUsd() *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearDailyLimitUsd()
	return _u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetMonthlyLimitUsd(v float64) *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.ResetMonthlyLimitUsd()
	_u.mutation.SetMonthlyLimitUsd(v)
	return _u
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetNillableMonthlyLimitUsd(v *float64) *BundleSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetMonthlyLimitUsd(*v)
	}
	return _u
}

// AddMonthlyLimitUsd adds value to the "monthly_limit_usd" field.
func (_u *BundleSubscriptionEntitlementUpdateOne) AddMonthlyLimitUsd(v float64) *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.AddMonthlyLimitUsd(v)
	return _u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (_u *BundleSubscriptionEntitlementUpdateOne) ClearMonthlyLimitUsd() *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearMonthlyLimitUsd()
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetDailyUsageUsd(v float64) *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetNillableDailyUsageUsd(v *float64) *BundleSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *BundleSubscriptionEntitlementUpdateOne) AddDailyUsageUsd(v float64) *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetMonthlyUsageUsd(v float64) *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetNillableMonthlyUsageUsd(v *float64) *BundleSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *BundleSubscriptionEntitlementUpdateOne) AddMonthlyUsageUsd(v float64) *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetSubscriptionID sets the "subscription" edge to the BundleSubscription entity by ID.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetSubscriptionID(id int64) *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.SetSubscriptionID(id)
	return _u
}

// SetSubscription sets the "subscription" edge to the BundleSubscription entity.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetSubscription(v *BundleSubscription) *BundleSubscriptionEntitlementUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *BundleSubscriptionEntitlementUpdateOne) SetGroup(v *Group) *BundleSubscriptionEntitlementUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the BundleSubscriptionEntitlementMutation object of the builder.
func (_u *BundleSubscriptionEntitlementUpdateOne) Mutation() *BundleSubscriptionEntitlementMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the BundleSubscription entity.
func (_u *BundleSubscriptionEntitlementUpdateOne) ClearSubscription() *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *BundleSubscriptionEntitlementUpdateOne) ClearGroup() *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the BundleSubscriptionEntitlementUpdate builder.
func (_u *BundleSubscriptionEntitlementUpdateOne) Where(ps ...predicate.BundleSubscriptionEntitlement) *BundleSubscriptionEntitlementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BundleSubscriptionEntitlementUpdateOne) Select(field string, fields ...string) *BundleSubscriptionEntitlementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BundleSubscriptionEntitlement entity.
func (_u *BundleSubscriptionEntitlementUpdateOne) Save(ctx context.Context) (*BundleSubscriptionEntitlement, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundleSubscriptionEntitlementUpdateOne) SaveX(ctx context.Context) *BundleSubscriptionEntitlement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BundleSubscriptionEntitlementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundleSubscriptionEntitlementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BundleSubscriptionEntitlementUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := bundlesubscriptionentitlement.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "BundleSubscriptionEntitlement.platform": %w`, err)}
		}
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleSubscriptionEntitlement.subscription"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleSubscriptionEntitlement.group"`)
	}
	return nil
}

func (_u *BundleSubscriptionEntitlementUpdateOne) sqlSave(ctx context.Context) (_node *BundleSubscriptionEntitlement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundlesubscriptionentitlement.Table, bundlesubscriptionentitlement.Columns, sqlgraph.NewFieldSpec(bundlesubscriptionentitlement.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BundleSubscriptionEntitlement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bundlesubscriptionentitlement.FieldID)
		for _, f := range fields {
			if !bundlesubscriptionentitlement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bundlesubscriptionentitlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(bundlesubscriptionentitlement.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.DailyLimitUsdCleared() {
		_spec.ClearField(bundlesubscriptionentitlement.FieldDailyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsd(); ok {
		_spec.AddField(bundlesubscriptionentitlement.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyLimitUsdCleared() {
		_spec.ClearField(bundlesubscriptionentitlement.FieldMonthlyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(bundlesubscriptionentitlement.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(bundlesubscriptionentitlement.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(bundlesubscriptionentitlement.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscriptionentitlement.SubscriptionTable,
			Columns: []string{bundlesubscriptionentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscriptionentitlement.SubscriptionTable,
			Columns: []string{bundlesubscriptionentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscriptionentitlement.GroupTable,
			Columns: []string{bundlesubscriptionentitlement.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscriptionentitlement.GroupTable,
			Columns: []string{bundlesubscriptionentitlement.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BundleSubscriptionEntitlement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundlesubscriptionentitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
