// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscription"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscriptionentitlement"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// BundleSubscriptionEntitlement is the model entity for the BundleSubscriptionEntitlement schema.
type BundleSubscriptionEntitlement struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// BundleSubscriptionID holds the value of the "bundle_subscription_id" field.
	BundleSubscriptionID int64 `json:"bundle_subscription_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// DailyLimitUsd holds the value of the "daily_limit_usd" field.
	DailyLimitUsd *float64 `json:"daily_limit_usd,omitempty"`
	// MonthlyLimitUsd holds the value of the "monthly_limit_usd" field.
	MonthlyLimitUsd *float64 `json:"monthly_limit_usd,omitempty"`
	// DailyUsageUsd holds the value of the "daily_usage_usd" field.
	DailyUsageUsd float64 `json:"daily_usage_usd,omitempty"`
	// MonthlyUsageUsd holds the value of the "monthly_usage_usd" field.
	MonthlyUsageUsd float64 `json:"monthly_usage_usd,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BundleSubscriptionEntitlementQuery when eager-loading is set.
	Edges        BundleSubscriptionEntitlementEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BundleSubscriptionEntitlementEdges holds the relations/edges for other nodes in the graph.
type BundleSubscriptionEntitlementEdges struct {
	// Subscription holds the value of the subscription edge.
	Subscription *BundleSubscription `json:"subscription,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BundleSubscriptionEntitlementEdges) SubscriptionOrErr() (*BundleSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: bundlesubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BundleSubscriptionEntitlementEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BundleSubscriptionEntitlement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bundlesubscriptionentitlement.FieldDailyLimitUsd, bundlesubscriptionentitlement.FieldMonthlyLimitUsd, bundlesubscriptionentitlement.FieldDailyUsageUsd, bundlesubscriptionentitlement.FieldMonthlyUsageUsd:
			values[i] = new(sql.NullFloat64)
		case bundlesubscriptionentitlement.FieldID, bundlesubscriptionentitlement.FieldBundleSubscriptionID, bundlesubscriptionentitlement.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case bundlesubscriptionentitlement.FieldPlatform:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BundleSubscriptionEntitlement fields.
func (_m *BundleSubscriptionEntitlement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bundlesubscriptionentitlement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case bundlesubscriptionentitlement.FieldBundleSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bundle_subscription_id", values[i])
			} else if value.Valid {
				_m.BundleSubscriptionID = value.Int64
			}
		case bundlesubscriptionentitlement.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case bundlesubscriptionentitlement.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case bundlesubscriptionentitlement.FieldDailyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit_usd", values[i])
			} else if value.Valid {
				_m.DailyLimitUsd = new(float64)
				*_m.DailyLimitUsd = value.Float64
			}
		case bundlesubscriptionentitlement.FieldMonthlyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_limit_usd", values[i])
			} else if value.Valid {
				_m.MonthlyLimitUsd = new(float64)
				*_m.MonthlyLimitUsd = value.Float64
			}
		case bundlesubscriptionentitlement.FieldDailyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_usage_usd", values[i])
			} else if value.Valid {
				_m.DailyUsageUsd = value.Float64
			}
		case bundlesubscriptionentitlement.FieldMonthlyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_usage_usd", values[i])
			} else if value.Valid {
				_m.MonthlyUsageUsd = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BundleSubscriptionEntitlement.
// This includes values selected through modifiers, order, etc.
func (_m *BundleSubscriptionEntitlement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySubscription queries the "subscription" edge of the BundleSubscriptionEntitlement entity.
func (_m *BundleSubscriptionEntitlement) QuerySubscription() *BundleSubscriptionQuery {
	return NewBundleSubscriptionEntitlementClient(_m.config).QuerySubscription(_m)
}

// QueryGroup queries the "group" edge of the BundleSubscriptionEntitlement entity.
func (_m *BundleSubscriptionEntitlement) QueryGroup() *GroupQuery {
	return NewBundleSubscriptionEntitlementClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this BundleSubscriptionEntitlement.
// Note that you need to call BundleSubscriptionEntitlement.Unwrap() before calling this method if this BundleSubscriptionEntitlement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BundleSubscriptionEntitlement) Update() *BundleSubscriptionEntitlementUpdateOne {
	return NewBundleSubscriptionEntitlementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BundleSubscriptionEntitlement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BundleSubscriptionEntitlement) Unwrap() *BundleSubscriptionEntitlement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BundleSubscriptionEntitlement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BundleSubscriptionEntitlement) String() string {
	var builder strings.Builder
	builder.WriteString("BundleSubscriptionEntitlement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("bundle_subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BundleSubscriptionID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	if v := _m.DailyLimitUsd; v != nil {
		builder.WriteString("daily_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MonthlyLimitUsd; v != nil {
		builder.WriteString("monthly_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("daily_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("monthly_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyUsageUsd))
	builder.WriteByte(')')
	return builder.String()
}

// BundleSubscriptionEntitlements is a parsable slice of BundleSubscriptionEntitlement.
type BundleSubscriptionEntitlements []*BundleSubscriptionEntitlement
