// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/bundleplan"
	"github.com/Wei-Shaw/sub2api/ent/bundleplangroup"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// BundlePlanGroup is the model entity for the BundlePlanGroup schema.
type BundlePlanGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// BundlePlanID holds the value of the "bundle_plan_id" field.
	BundlePlanID int64 `json:"bundle_plan_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// DailyLimitUsd holds the value of the "daily_limit_usd" field.
	DailyLimitUsd *float64 `json:"daily_limit_usd,omitempty"`
	// MonthlyLimitUsd holds the value of the "monthly_limit_usd" field.
	MonthlyLimitUsd *float64 `json:"monthly_limit_usd,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BundlePlanGroupQuery when eager-loading is set.
	Edges        BundlePlanGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BundlePlanGroupEdges holds the relations/edges for other nodes in the graph.
type BundlePlanGroupEdges struct {
	// Plan holds the value of the plan edge.
	Plan *BundlePlan `json:"plan,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BundlePlanGroupEdges) PlanOrErr() (*BundlePlan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: bundleplan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BundlePlanGroupEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BundlePlanGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bundleplangroup.FieldDailyLimitUsd, bundleplangroup.FieldMonthlyLimitUsd:
			values[i] = new(sql.NullFloat64)
		case bundleplangroup.FieldID, bundleplangroup.FieldBundlePlanID, bundleplangroup.FieldGroupID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BundlePlanGroup fields.
func (_m *BundlePlanGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bundleplangroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case bundleplangroup.FieldBundlePlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bundle_plan_id", values[i])
			} else if value.Valid {
				_m.BundlePlanID = value.Int64
			}
		case bundleplangroup.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case bundleplangroup.FieldDailyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit_usd", values[i])
			} else if value.Valid {
				_m.DailyLimitUsd = new(float64)
				*_m.DailyLimitUsd = value.Float64
			}
		case bundleplangroup.FieldMonthlyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_limit_usd", values[i])
			} else if value.Valid {
				_m.MonthlyLimitUsd = new(float64)
				*_m.MonthlyLimitUsd = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BundlePlanGroup.
// This includes values selected through modifiers, order, etc.
func (_m *BundlePlanGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlan queries the "plan" edge of the BundlePlanGroup entity.
func (_m *BundlePlanGroup) QueryPlan() *BundlePlanQuery {
	return NewBundlePlanGroupClient(_m.config).QueryPlan(_m)
}

// QueryGroup queries the "group" edge of the BundlePlanGroup entity.
func (_m *BundlePlanGroup) QueryGroup() *GroupQuery {
	return NewBundlePlanGroupClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this BundlePlanGroup.
// Note that you need to call BundlePlanGroup.Unwrap() before calling this method if this BundlePlanGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BundlePlanGroup) Update() *BundlePlanGroupUpdateOne {
	return NewBundlePlanGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BundlePlanGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BundlePlanGroup) Unwrap() *BundlePlanGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BundlePlanGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BundlePlanGroup) String() string {
	var builder strings.Builder
	builder.WriteString("BundlePlanGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("bundle_plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BundlePlanID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	if v := _m.DailyLimitUsd; v != nil {
		builder.WriteString("daily_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MonthlyLimitUsd; v != nil {
		builder.WriteString("monthly_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// BundlePlanGroups is a parsable slice of BundlePlanGroup.
type BundlePlanGroups []*BundlePlanGroup
