// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bundleplan"
	"github.com/Wei-Shaw/sub2api/ent/bundleplangroup"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// BundlePlanGroupCreate is the builder for creating a BundlePlanGroup entity.
type BundlePlanGroupCreate struct {
	config
	mutation *BundlePlanGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBundlePlanID sets the "bundle_plan_id" field.
func (_c *BundlePlanGroupCreate) SetBundlePlanID(v int64) *BundlePlanGroupCreate {
	_c.mutation.SetBundlePlanID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *BundlePlanGroupCreate) SetGroupID(v int64) *BundlePlanGroupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_c *BundlePlanGroupCreate) SetDailyLimitUsd(v float64) *BundlePlanGroupCreate {
	_c.mutation.SetDailyLimitUsd(v)
	return _c
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_c *BundlePlanGroupCreate) SetNillableDailyLimitUsd(v *float64) *BundlePlanGroupCreate {
	if v != nil {
		_c.SetDailyLimitUsd(*v)
	}
	return _c
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_c *BundlePlanGroupCreate) SetMonthlyLimitUsd(v float64) *BundlePlanGroupCreate {
	_c.mutation.SetMonthlyLimitUsd(v)
	return _c
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_c *BundlePlanGroupCreate) SetNillableMonthlyLimitUsd(v *float64) *BundlePlanGroupCreate {
	if v != nil {
		_c.SetMonthlyLimitUsd(*v)
	}
	return _c
}

// SetPlanID sets the "plan" edge to the BundlePlan entity by ID.
func (_c *BundlePlanGroupCreate) SetPlanID(id int64) *BundlePlanGroupCreate {
	_c.mutation.SetPlanID(id)
	return _c
}

// SetPlan sets the "plan" edge to the BundlePlan entity.
func (_c *BundlePlanGroupCreate) SetPlan(v *BundlePlan) *BundlePlanGroupCreate {
	return _c.SetPlanID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *BundlePlanGroupCreate) SetGroup(v *Group) *BundlePlanGroupCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the BundlePlanGroupMutation object of the builder.
func (_c *BundlePlanGroupCreate) Mutation() *BundlePlanGroupMutation {
	return _c.mutation
}

// Save creates the BundlePlanGroup in the database.
func (_c *BundlePlanGroupCreate) Save(ctx context.Context) (*BundlePlanGroup, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BundlePlanGroupCreate) SaveX(ctx context.Context) *BundlePlanGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BundlePlanGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BundlePlanGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BundlePlanGroupCreate) check() error {
	if _, ok := _c.mutation.BundlePlanID(); !ok {
		return &ValidationError{Name: "bundle_plan_id", err: errors.New(`ent: missing required field "BundlePlanGroup.bundle_plan_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "BundlePlanGroup.group_id"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "BundlePlanGroup.plan"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "BundlePlanGroup.group"`)}
	}
	return nil
}

func (_c *BundlePlanGroupCreate) sqlSave(ctx context.Context) (*BundlePlanGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BundlePlanGroupCreate) createSpec() (*BundlePlanGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &BundlePlanGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bundleplangroup.Table, sqlgraph.NewFieldSpec(bundleplangroup.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.DailyLimitUsd(); ok {
		_spec.SetField(bundleplangroup.FieldDailyLimitUsd, field.TypeFloat64, value)
		_node.DailyLimitUsd = &value
	}
	if value, ok := _c.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(bundleplangroup.FieldMonthlyLimitUsd, field.TypeFloat64, value)
		_node.MonthlyLimitUsd = &value
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleplangroup.PlanTable,
			Columns: []string{bundleplangroup.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BundlePlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleplangroup.GroupTable,
			Columns: []string{bundleplangroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BundlePlanGroup.Create().
//		SetBundlePlanID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BundlePlanGroupUpsert) {
//			SetBundlePlanID(v+v).
//		}).
//		Exec(ctx)
func (_c *BundlePlanGroupCreate) OnConflict(opts ...sql.ConflictOption) *BundlePlanGroupUpsertOne {
	_c.conflict = opts
	return &BundlePlanGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BundlePlanGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BundlePlanGroupCreate) OnConflictColumns(columns ...string) *BundlePlanGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BundlePlanGroupUpsertOne{
		create: _c,
	}
}

type (
	// BundlePlanGroupUpsertOne is the builder for "upsert"-ing
	//  one BundlePlanGroup node.
	BundlePlanGroupUpsertOne struct {
		create *BundlePlanGroupCreate
	}

	// BundlePlanGroupUpsert is the "OnConflict" setter.
	BundlePlanGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetBundlePlanID sets the "bundle_plan_id" field.
func (u *BundlePlanGroupUpsert) SetBundlePlanID(v int64) *BundlePlanGroupUpsert {
	u.Set(bundleplangroup.FieldBundlePlanID, v)
	return u
}

// UpdateBundlePlanID sets the "bundle_plan_id" field to the value that was provided on create.
func (u *BundlePlanGroupUpsert) UpdateBundlePlanID() *BundlePlanGroupUpsert {
	u.SetExcluded(bundleplangroup.FieldBundlePlanID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *BundlePlanGroupUpsert) SetGroupID(v int64) *BundlePlanGroupUpsert {
	u.Set(bundleplangroup.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BundlePlanGroupUpsert) UpdateGroupID() *BundlePlanGroupUpsert {
	u.SetExcluded(bundleplangroup.FieldGroupID)
	return u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *BundlePlanGroupUpsert) SetDailyLimitUsd(v float64) *BundlePlanGroupUpsert {
	u.Set(bundleplangroup.FieldDailyLimitUsd, v)
	return u
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupUpsert) UpdateDailyLimitUsd() *BundlePlanGroupUpsert {
	u.SetExcluded(bundleplangroup.FieldDailyLimitUsd)
	return u
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *BundlePlanGroupUpsert) AddDailyLimitUsd(v float64) *BundlePlanGroupUpsert {
	u.Add(bundleplangroup.FieldDailyLimitUsd, v)
	return u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *BundlePlanGroupUpsert) ClearDailyLimitUsd() *BundlePlanGroupUpsert {
	u.SetNull(bundleplangroup.FieldDailyLimitUsd)
	return u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *BundlePlanGroupUpsert) SetMonthlyLimitUsd(v float64) *BundlePlanGroupUpsert {
	u.Set(bundleplangroup.FieldMonthlyLimitUsd, v)
	return u
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupUpsert) UpdateMonthlyLimitUsd() *BundlePlanGroupUpsert {
	u.SetExcluded(bundleplangroup.FieldMonthlyLimitUsd)
	return u
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *BundlePlanGroupUpsert) AddMonthlyLimitUsd(v float64) *BundlePlanGroupUpsert {
	u.Add(bundleplangroup.FieldMonthlyLimitUsd, v)
	return u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *BundlePlanGroupUpsert) ClearMonthlyLimitUsd() *BundlePlanGroupUpsert {
	u.SetNull(bundleplangroup.FieldMonthlyLimitUsd)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BundlePlanGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BundlePlanGroupUpsertOne) UpdateNewValues() *BundlePlanGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BundlePlanGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BundlePlanGroupUpsertOne) Ignore() *BundlePlanGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BundlePlanGroupUpsertOne) DoNothing() *BundlePlanGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BundlePlanGroupCreate.OnConflict
// documentation for more info.
func (u *BundlePlanGroupUpsertOne) Update(set func(*BundlePlanGroupUpsert)) *BundlePlanGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BundlePlanGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetBundlePlanID sets the "bundle_plan_id" field.
func (u *BundlePlanGroupUpsertOne) SetBundlePlanID(v int64) *BundlePlanGroupUpsertOne {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.SetBundlePlanID(v)
	})
}

// UpdateBundlePlanID sets the "bundle_plan_id" field to the value that was provided on create.
func (u *BundlePlanGroupUpsertOne) UpdateBundlePlanID() *BundlePlanGroupUpsertOne {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.UpdateBundlePlanID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *BundlePlanGroupUpsertOne) SetGroupID(v int64) *BundlePlanGroupUpsertOne {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BundlePlanGroupUpsertOne) UpdateGroupID() *BundlePlanGroupUpsertOne {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.UpdateGroupID()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *BundlePlanGroupUpsertOne) SetDailyLimitUsd(v float64) *BundlePlanGroupUpsertOne {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *BundlePlanGroupUpsertOne) AddDailyLimitUsd(v float64) *BundlePlanGroupUpsertOne {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupUpsertOne) UpdateDailyLimitUsd() *BundlePlanGroupUpsertOne {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *BundlePlanGroupUpsertOne) ClearDailyLimitUsd() *BundlePlanGroupUpsertOne {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.ClearDailyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *BundlePlanGroupUpsertOne) SetMonthlyLimitUsd(v float64) *BundlePlanGroupUpsertOne {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *BundlePlanGroupUpsertOne) AddMonthlyLimitUsd(v float64) *BundlePlanGroupUpsertOne {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupUpsertOne) UpdateMonthlyLimitUsd() *BundlePlanGroupUpsertOne {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *BundlePlanGroupUpsertOne) ClearMonthlyLimitUsd() *BundlePlanGroupUpsertOne {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.ClearMonthlyLimitUsd()
	})
}

// Exec executes the query.
func (u *BundlePlanGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BundlePlanGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BundlePlanGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BundlePlanGroupUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BundlePlanGroupUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BundlePlanGroupCreateBulk is the builder for creating many BundlePlanGroup entities in bulk.
type BundlePlanGroupCreateBulk struct {
	config
	err      error
	builders []*BundlePlanGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the BundlePlanGroup entities in the database.
func (_c *BundlePlanGroupCreateBulk) Save(ctx context.Context) ([]*BundlePlanGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BundlePlanGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BundlePlanGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BundlePlanGroupCreateBulk) SaveX(ctx context.Context) []*BundlePlanGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BundlePlanGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BundlePlanGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BundlePlanGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BundlePlanGroupUpsert) {
//			SetBundlePlanID(v+v).
//		}).
//		Exec(ctx)
func (_c *BundlePlanGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *BundlePlanGroupUpsertBulk {
	_c.conflict = opts
	return &BundlePlanGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BundlePlanGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BundlePlanGroupCreateBulk) OnConflictColumns(columns ...string) *BundlePlanGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BundlePlanGroupUpsertBulk{
		create: _c,
	}
}

// BundlePlanGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of BundlePlanGroup nodes.
type BundlePlanGroupUpsertBulk struct {
	create *BundlePlanGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BundlePlanGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BundlePlanGroupUpsertBulk) UpdateNewValues() *BundlePlanGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BundlePlanGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BundlePlanGroupUpsertBulk) Ignore() *BundlePlanGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BundlePlanGroupUpsertBulk) DoNothing() *BundlePlanGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BundlePlanGroupCreateBulk.OnConflict
// documentation for more info.
func (u *BundlePlanGroupUpsertBulk) Update(set func(*BundlePlanGroupUpsert)) *BundlePlanGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BundlePlanGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetBundlePlanID sets the "bundle_plan_id" field.
func (u *BundlePlanGroupUpsertBulk) SetBundlePlanID(v int64) *BundlePlanGroupUpsertBulk {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.SetBundlePlanID(v)
	})
}

// UpdateBundlePlanID sets the "bundle_plan_id" field to the value that was provided on create.
func (u *BundlePlanGroupUpsertBulk) UpdateBundlePlanID() *BundlePlanGroupUpsertBulk {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.UpdateBundlePlanID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *BundlePlanGroupUpsertBulk) SetGroupID(v int64) *BundlePlanGroupUpsertBulk {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BundlePlanGroupUpsertBulk) UpdateGroupID() *BundlePlanGroupUpsertBulk {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.UpdateGroupID()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *BundlePlanGroupUpsertBulk) SetDailyLimitUsd(v float64) *BundlePlanGroupUpsertBulk {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *BundlePlanGroupUpsertBulk) AddDailyLimitUsd(v float64) *BundlePlanGroupUpsertBulk {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupUpsertBulk) UpdateDailyLimitUsd() *BundlePlanGroupUpsertBulk {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *BundlePlanGroupUpsertBulk) ClearDailyLimitUsd() *BundlePlanGroupUpsertBulk {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.ClearDailyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *BundlePlanGroupUpsertBulk) SetMonthlyLimitUsd(v float64) *BundlePlanGroupUpsertBulk {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *BundlePlanGroupUpsertBulk) AddMonthlyLimitUsd(v float64) *BundlePlanGroupUpsertBulk {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupUpsertBulk) UpdateMonthlyLimitUsd() *BundlePlanGroupUpsertBulk {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *BundlePlanGroupUpsertBulk) ClearMonthlyLimitUsd() *BundlePlanGroupUpsertBulk {
	return u.Update(func(s *BundlePlanGroupUpsert) {
		s.ClearMonthlyLimitUsd()
	})
}

// Exec executes the query.
func (u *BundlePlanGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BundlePlanGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BundlePlanGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BundlePlanGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
