// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bundleplan"
	"github.com/Wei-Shaw/sub2api/ent/bundleplangroup"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BundlePlanGroupUpdate is the builder for updating BundlePlanGroup entities.
type BundlePlanGroupUpdate struct {
	config
	hooks    []Hook
	mutation *BundlePlanGroupMutation
}

// Where appends a list predicates to the BundlePlanGroupUpdate builder.
func (_u *BundlePlanGroupUpdate) Where(ps ...predicate.BundlePlanGroup) *BundlePlanGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBundlePlanID sets the "bundle_plan_id" field.
func (_u *BundlePlanGroupUpdate) SetBundlePlanID(v int64) *BundlePlanGroupUpdate {
	_u.mutation.SetBundlePlanID(v)
	return _u
}

// SetNillableBundlePlanID sets the "bundle_plan_id" field if the given value is not nil.
func (_u *BundlePlanGroupUpdate) SetNillableBundlePlanID(v *int64) *BundlePlanGroupUpdate {
	if v != nil {
		_u.SetBundlePlanID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *BundlePlanGroupUpdate) SetGroupID(v int64) *BundlePlanGroupUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *BundlePlanGroupUpdate) SetNillableGroupID(v *int64) *BundlePlanGroupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *BundlePlanGroupUpdate) SetDailyLimitUsd(v float64) *BundlePlanGroupUpdate {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *BundlePlanGroupUpdate) SetNillableDailyLimitUsd(v *float64) *BundlePlanGroupUpdate {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *BundlePlanGroupUpdate) AddDailyLimitUsd(v float64) *BundlePlanGroupUpdate {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (_u *BundlePlanGroupUpdate) ClearDailyLimitUsd() *BundlePlanGroupUpdate {
	_u.mutation.ClearDailyLimitUsd()
	return _u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_u *BundlePlanGroupUpdate) SetMonthlyLimitUsd(v float64) *BundlePlanGroupUpdate {
	_u.mutation.ResetMonthlyLimitUsd()
	_u.mutation.SetMonthlyLimitUsd(v)
	return _u
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_u *BundlePlanGroupUpdate) SetNillableMonthlyLimitUsd(v *float64) *BundlePlanGroupUpdate {
	if v != nil {
		_u.SetMonthlyLimitUsd(*v)
	}
	return _u
}

// AddMonthlyLimitUsd adds value to the "monthly_limit_usd" field.
func (_u *BundlePlanGroupUpdate) AddMonthlyLimitUsd(v float64) *BundlePlanGroupUpdate {
	_u.mutation.AddMonthlyLimitUsd(v)
	return _u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (_u *BundlePlanGroupUpdate) ClearMonthlyLimitUsd() *BundlePlanGroupUpdate {
	_u.mutation.ClearMonthlyLimitUsd()
	return _u
}

// SetPlanID sets the "plan" edge to the BundlePlan entity by ID.
func (_u *BundlePlanGroupUpdate) SetPlanID(id int64) *BundlePlanGroupUpdate {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the BundlePlan entity.
func (_u *BundlePlanGroupUpdate) SetPlan(v *BundlePlan) *BundlePlanGroupUpdate {
	return _u.SetPlanID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *BundlePlanGroupUpdate) SetGroup(v *Group) *BundlePlanGroupUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the BundlePlanGroupMutation object of the builder.
func (_u *BundlePlanGroupUpdate) Mutation() *BundlePlanGroupMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the BundlePlan entity.
func (_u *BundlePlanGroupUpdate) ClearPlan() *BundlePlanGroupUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *BundlePlanGroupUpdate) ClearGroup() *BundlePlanGroupUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BundlePlanGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundlePlanGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BundlePlanGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundlePlanGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BundlePlanGroupUpdate) check() error {
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundlePlanGroup.plan"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundlePlanGroup.group"`)
	}
	return nil
}

func (_u *BundlePlanGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundleplangroup.Table, bundleplangroup.Columns, sqlgraph.NewFieldSpec(bundleplangroup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(bundleplangroup.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(bundleplangroup.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.DailyLimitUsdCleared() {
		_spec.ClearField(bundleplangroup.FieldDailyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(bundleplangroup.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsd(); ok {
		_spec.AddField(bundleplangroup.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyLimitUsdCleared() {
		_spec.ClearField(bundleplangroup.FieldMonthlyLimitUsd, field.TypeFloat64)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleplangroup.PlanTable,
			Columns: []string{bundleplangroup.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleplangroup.PlanTable,
			Columns: []string{bundleplangroup.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleplangroup.GroupTable,
			Columns: []string{bundleplangroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleplangroup.GroupTable,
			Columns: []string{bundleplangroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundleplangroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BundlePlanGroupUpdateOne is the builder for updating a single BundlePlanGroup entity.
type BundlePlanGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BundlePlanGroupMutation
}

// SetBundlePlanID sets the "bundle_plan_id" field.
func (_u *BundlePlanGroupUpdateOne) SetBundlePlanID(v int64) *BundlePlanGroupUpdateOne {
	_u.mutation.SetBundlePlanID(v)
	return _u
}

// SetNillableBundlePlanID sets the "bundle_plan_id" field if the given value is not nil.
func (_u *BundlePlanGroupUpdateOne) SetNillableBundlePlanID(v *int64) *BundlePlanGroupUpdateOne {
	if v != nil {
		_u.SetBundlePlanID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *BundlePlanGroupUpdateOne) SetGroupID(v int64) *BundlePlanGroupUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *BundlePlanGroupUpdateOne) SetNillableGroupID(v *int64) *BundlePlanGroupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *BundlePlanGroupUpdateOne) SetDailyLimitUsd(v float64) *BundlePlanGroupUpdateOne {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *BundlePlanGroupUpdateOne) SetNillableDailyLimitUsd(v *float64) *BundlePlanGroupUpdateOne {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *BundlePlanGroupUpdateOne) AddDailyLimitUsd(v float64) *BundlePlanGroupUpdateOne {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (_u *BundlePlanGroupUpdateOne) ClearDailyLimitUsd() *BundlePlanGroupUpdateOne {
	_u.mutation.ClearDailyLimitUsd()
	return _u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_u *BundlePlanGroupUpdateOne) SetMonthlyLimitUsd(v float64) *BundlePlanGroupUpdateOne {
	_u.mutation.ResetMonthlyLimitUsd()
	_u.mutation.SetMonthlyLimitUsd(v)
	return _u
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_u *BundlePlanGroupUpdateOne) SetNillableMonthlyLimitUsd(v *float64) *BundlePlanGroupUpdateOne {
	if v != nil {
		_u.SetMonthlyLimitUsd(*v)
	}
	return _u
}

// AddMonthlyLimitUsd adds value to the "monthly_limit_usd" field.
func (_u *BundlePlanGroupUpdateOne) AddMonthlyLimitUsd(v float64) *BundlePlanGroupUpdateOne {
	_u.mutation.AddMonthlyLimitUsd(v)
	return _u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (_u *BundlePlanGroupUpdateOne) ClearMonthlyLimitUsd() *BundlePlanGroupUpdateOne {
	_u.mutation.ClearMonthlyLimitUsd()
	return _u
}

// SetPlanID sets the "plan" edge to the BundlePlan entity by ID.
func (_u *BundlePlanGroupUpdateOne) SetPlanID(id int64) *BundlePlanGroupUpdateOne {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the BundlePlan entity.
func (_u *BundlePlanGroupUpdateOne) SetPlan(v *BundlePlan) *BundlePlanGroupUpdateOne {
	return _u.SetPlanID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *BundlePlanGroupUpdateOne) SetGroup(v *Group) *BundlePlanGroupUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the BundlePlanGroupMutation object of the builder.
func (_u *BundlePlanGroupUpdateOne) Mutation() *BundlePlanGroupMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the BundlePlan entity.
func (_u *BundlePlanGroupUpdateOne) ClearPlan() *BundlePlanGroupUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *BundlePlanGroupUpdateOne) ClearGroup() *BundlePlanGroupUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the BundlePlanGroupUpdate builder.
func (_u *BundlePlanGroupUpdateOne) Where(ps ...predicate.BundlePlanGroup) *BundlePlanGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BundlePlanGroupUpdateOne) Select(field string, fields ...string) *BundlePlanGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BundlePlanGroup entity.
func (_u *BundlePlanGroupUpdateOne) Save(ctx context.Context) (*BundlePlanGroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundlePlanGroupUpdateOne) SaveX(ctx context.Context) *BundlePlanGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BundlePlanGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundlePlanGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BundlePlanGroupUpdateOne) check() error {
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundlePlanGroup.plan"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundlePlanGroup.group"`)
	}
	return nil
}

func (_u *BundlePlanGroupUpdateOne) sqlSave(ctx context.Context) (_node *BundlePlanGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundleplangroup.Table, bundleplangroup.Columns, sqlgraph.NewFieldSpec(bundleplangroup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BundlePlanGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bundleplangroup.FieldID)
		for _, f := range fields {
			if !bundleplangroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bundleplangroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(bundleplangroup.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(bundleplangroup.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.DailyLimitUsdCleared() {
		_spec.ClearField(bundleplangroup.FieldDailyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(bundleplangroup.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsd(); ok {
		_spec.AddField(bundleplangroup.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyLimitUsdCleared() {
		_spec.ClearField(bundleplangroup.FieldMonthlyLimitUsd, field.TypeFloat64)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleplangroup.PlanTable,
			Columns: []string{bundleplangroup.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleplangroup.PlanTable,
			Columns: []string{bundleplangroup.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleplangroup.GroupTable,
			Columns: []string{bundleplangroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleplangroup.GroupTable,
			Columns: []string{bundleplangroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BundlePlanGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundleplangroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
