// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bundleplangroup"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BundlePlanGroupDelete is the builder for deleting a BundlePlanGroup entity.
type BundlePlanGroupDelete struct {
	config
	hooks    []Hook
	mutation *BundlePlanGroupMutation
}

// Where appends a list predicates to the BundlePlanGroupDelete builder.
func (_d *BundlePlanGroupDelete) Where(ps ...predicate.BundlePlanGroup) *BundlePlanGroupDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BundlePlanGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BundlePlanGroupDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BundlePlanGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(bundleplangroup.Table, sqlgraph.NewFieldSpec(bundleplangroup.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BundlePlanGroupDeleteOne is the builder for deleting a single BundlePlanGroup entity.
type BundlePlanGroupDeleteOne struct {
	_d *BundlePlanGroupDelete
}

// Where appends a list predicates to the BundlePlanGroupDelete builder.
func (_d *BundlePlanGroupDeleteOne) Where(ps ...predicate.BundlePlanGroup) *BundlePlanGroupDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BundlePlanGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bundleplangroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BundlePlanGroupDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
