// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bundleplan"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscription"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscriptionentitlement"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// BundleSubscriptionUpdate is the builder for updating BundleSubscription entities.
type BundleSubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *BundleSubscriptionMutation
}

// Where appends a list predicates to the BundleSubscriptionUpdate builder.
func (_u *BundleSubscriptionUpdate) Where(ps ...predicate.BundleSubscription) *BundleSubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BundleSubscriptionUpdate) SetUserID(v int64) *BundleSubscriptionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BundleSubscriptionUpdate) SetNillableUserID(v *int64) *BundleSubscriptionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBundlePlanID sets the "bundle_plan_id" field.
func (_u *BundleSubscriptionUpdate) SetBundlePlanID(v int64) *BundleSubscriptionUpdate {
	_u.mutation.SetBundlePlanID(v)
	return _u
}

// SetNillableBundlePlanID sets the "bundle_plan_id" field if the given value is not nil.
func (_u *BundleSubscriptionUpdate) SetNillableBundlePlanID(v *int64) *BundleSubscriptionUpdate {
	if v != nil {
		_u.SetBundlePlanID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BundleSubscriptionUpdate) SetStatus(v string) *BundleSubscriptionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BundleSubscriptionUpdate) SetNillableStatus(v *string) *BundleSubscriptionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *BundleSubscriptionUpdate) SetStartsAt(v time.Time) *BundleSubscriptionUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *BundleSubscriptionUpdate) SetNillableStartsAt(v *time.Time) *BundleSubscriptionUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *BundleSubscriptionUpdate) SetExpiresAt(v time.Time) *BundleSubscriptionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *BundleSubscriptionUpdate) SetNillableExpiresAt(v *time.Time) *BundleSubscriptionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_u *BundleSubscriptionUpdate) SetDailyWindowStart(v time.Time) *BundleSubscriptionUpdate {
	_u.mutation.SetDailyWindowStart(v)
	return _u
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_u *BundleSubscriptionUpdate) SetNillableDailyWindowStart(v *time.Time) *BundleSubscriptionUpdate {
	if v != nil {
		_u.SetDailyWindowStart(*v)
	}
	return _u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (_u *BundleSubscriptionUpdate) ClearDailyWindowStart() *BundleSubscriptionUpdate {
	_u.mutation.ClearDailyWindowStart()
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *BundleSubscriptionUpdate) SetMonthlyWindowStart(v time.Time) *BundleSubscriptionUpdate {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *BundleSubscriptionUpdate) SetNillableMonthlyWindowStart(v *time.Time) *BundleSubscriptionUpdate {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (_u *BundleSubscriptionUpdate) ClearMonthlyWindowStart() *BundleSubscriptionUpdate {
	_u.mutation.ClearMonthlyWindowStart()
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *BundleSubscriptionUpdate) SetDailyUsageUsd(v float64) *BundleSubscriptionUpdate {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *BundleSubscriptionUpdate) SetNillableDailyUsageUsd(v *float64) *BundleSubscriptionUpdate {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *BundleSubscriptionUpdate) AddDailyUsageUsd(v float64) *BundleSubscriptionUpdate {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *BundleSubscriptionUpdate) SetMonthlyUsageUsd(v float64) *BundleSubscriptionUpdate {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *BundleSubscriptionUpdate) SetNillableMonthlyUsageUsd(v *float64) *BundleSubscriptionUpdate {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *BundleSubscriptionUpdate) AddMonthlyUsageUsd(v float64) *BundleSubscriptionUpdate {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *BundleSubscriptionUpdate) SetPaymentOrderID(v int64) *BundleSubscriptionUpdate {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *BundleSubscriptionUpdate) SetNillablePaymentOrderID(v *int64) *BundleSubscriptionUpdate {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *BundleSubscriptionUpdate) AddPaymentOrderID(v int64) *BundleSubscriptionUpdate {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (_u *BundleSubscriptionUpdate) ClearPaymentOrderID() *BundleSubscriptionUpdate {
	_u.mutation.ClearPaymentOrderID()
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *BundleSubscriptionUpdate) SetAssignedBy(v int64) *BundleSubscriptionUpdate {
	_u.mutation.ResetAssignedBy()
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *BundleSubscriptionUpdate) SetNillableAssignedBy(v *int64) *BundleSubscriptionUpdate {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// AddAssignedBy adds value to the "assigned_by" field.
func (_u *BundleSubscriptionUpdate) AddAssignedBy(v int64) *BundleSubscriptionUpdate {
	_u.mutation.AddAssignedBy(v)
	return _u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (_u *BundleSubscriptionUpdate) ClearAssignedBy() *BundleSubscriptionUpdate {
	_u.mutation.ClearAssignedBy()
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *BundleSubscriptionUpdate) SetAssignedAt(v time.Time) *BundleSubscriptionUpdate {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *BundleSubscriptionUpdate) SetNillableAssignedAt(v *time.Time) *BundleSubscriptionUpdate {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *BundleSubscriptionUpdate) SetNotes(v string) *BundleSubscriptionUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *BundleSubscriptionUpdate) SetNillableNotes(v *string) *BundleSubscriptionUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *BundleSubscriptionUpdate) ClearNotes() *BundleSubscriptionUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BundleSubscriptionUpdate) SetUpdatedAt(v time.Time) *BundleSubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BundleSubscriptionUpdate) SetUser(v *User) *BundleSubscriptionUpdate {
	return _u.SetUserID(v.ID)
}

// SetPlanID sets the "plan" edge to the BundlePlan entity by ID.
func (_u *BundleSubscriptionUpdate) SetPlanID(id int64) *BundleSubscriptionUpdate {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the BundlePlan entity.
func (_u *BundleSubscriptionUpdate) SetPlan(v *BundlePlan) *BundleSubscriptionUpdate {
	return _u.SetPlanID(v.ID)
}

// AddEntitlementIDs adds the "entitlements" edge to the BundleSubscriptionEntitlement entity by IDs.
func (_u *BundleSubscriptionUpdate) AddEntitlementIDs(ids ...int64) *BundleSubscriptionUpdate {
	_u.mutation.AddEntitlementIDs(ids...)
	return _u
}

// AddEntitlements adds the "entitlements" edges to the BundleSubscriptionEntitlement entity.
func (_u *BundleSubscriptionUpdate) AddEntitlements(v ...*BundleSubscriptionEntitlement) *BundleSubscriptionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntitlementIDs(ids...)
}

// Mutation returns the BundleSubscriptionMutation object of the builder.
func (_u *BundleSubscriptionUpdate) Mutation() *BundleSubscriptionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BundleSubscriptionUpdate) ClearUser() *BundleSubscriptionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearPlan clears the "plan" edge to the BundlePlan entity.
func (_u *BundleSubscriptionUpdate) ClearPlan() *BundleSubscriptionUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// ClearEntitlements clears all "entitlements" edges to the BundleSubscriptionEntitlement entity.
func (_u *BundleSubscriptionUpdate) ClearEntitlements() *BundleSubscriptionUpdate {
	_u.mutation.ClearEntitlements()
	return _u
}

// RemoveEntitlementIDs removes the "entitlements" edge to BundleSubscriptionEntitlement entities by IDs.
func (_u *BundleSubscriptionUpdate) RemoveEntitlementIDs(ids ...int64) *BundleSubscriptionUpdate {
	_u.mutation.RemoveEntitlementIDs(ids...)
	return _u
}

// RemoveEntitlements removes "entitlements" edges to BundleSubscriptionEntitlement entities.
func (_u *BundleSubscriptionUpdate) RemoveEntitlements(v ...*BundleSubscriptionEntitlement) *BundleSubscriptionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntitlementIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BundleSubscriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundleSubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BundleSubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundleSubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BundleSubscriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bundlesubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BundleSubscriptionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := bundlesubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BundleSubscription.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleSubscription.user"`)
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleSubscription.plan"`)
	}
	return nil
}

func (_u *BundleSubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundlesubscription.Table, bundlesubscription.Columns, sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(bundlesubscription.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(bundlesubscription.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(bundlesubscription.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DailyWindowStart(); ok {
		_spec.SetField(bundlesubscription.FieldDailyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.DailyWindowStartCleared() {
		_spec.ClearField(bundlesubscription.FieldDailyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(bundlesubscription.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.MonthlyWindowStartCleared() {
		_spec.ClearField(bundlesubscription.FieldMonthlyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(bundlesubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(bundlesubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(bundlesubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(bundlesubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(bundlesubscription.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(bundlesubscription.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if _u.mutation.PaymentOrderIDCleared() {
		_spec.ClearField(bundlesubscription.FieldPaymentOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AssignedBy(); ok {
		_spec.SetField(bundlesubscription.FieldAssignedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAssignedBy(); ok {
		_spec.AddField(bundlesubscription.FieldAssignedBy, field.TypeInt64, value)
	}
	if _u.mutation.AssignedByCleared() {
		_spec.ClearField(bundlesubscription.FieldAssignedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(bundlesubscription.FieldAssignedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(bundlesubscription.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(bundlesubscription.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bundlesubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscription.UserTable,
			Columns: []string{bundlesubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscription.UserTable,
			Columns: []string{bundlesubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscription.PlanTable,
			Columns: []string{bundlesubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscription.PlanTable,
			Columns: []string{bundlesubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntitlementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundlesubscription.EntitlementsTable,
			Columns: []string{bundlesubscription.EntitlementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscriptionentitlement.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntitlementsIDs(); len(nodes) > 0 && !_u.mutation.EntitlementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundlesubscription.EntitlementsTable,
			Columns: []string{bundlesubscription.EntitlementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscriptionentitlement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntitlementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundlesubscription.EntitlementsTable,
			Columns: []string{bundlesubscription.EntitlementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscriptionentitlement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundlesubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BundleSubscriptionUpdateOne is the builder for updating a single BundleSubscription entity.
type BundleSubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BundleSubscriptionMutation
}

// SetUserID sets the "user_id" field.
func (_u *BundleSubscriptionUpdateOne) SetUserID(v int64) *BundleSubscriptionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BundleSubscriptionUpdateOne) SetNillableUserID(v *int64) *BundleSubscriptionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBundlePlanID sets the "bundle_plan_id" field.
func (_u *BundleSubscriptionUpdateOne) SetBundlePlanID(v int64) *BundleSubscriptionUpdateOne {
	_u.mutation.SetBundlePlanID(v)
	return _u
}

// SetNillableBundlePlanID sets the "bundle_plan_id" field if the given value is not nil.
func (_u *BundleSubscriptionUpdateOne) SetNillableBundlePlanID(v *int64) *BundleSubscriptionUpdateOne {
	if v != nil {
		_u.SetBundlePlanID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BundleSubscriptionUpdateOne) SetStatus(v string) *BundleSubscriptionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BundleSubscriptionUpdateOne) SetNillableStatus(v *string) *BundleSubscriptionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *BundleSubscriptionUpdateOne) SetStartsAt(v time.Time) *BundleSubscriptionUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *BundleSubscriptionUpdateOne) SetNillableStartsAt(v *time.Time) *BundleSubscriptionUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *BundleSubscriptionUpdateOne) SetExpiresAt(v time.Time) *BundleSubscriptionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *BundleSubscriptionUpdateOne) SetNillableExpiresAt(v *time.Time) *BundleSubscriptionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_u *BundleSubscriptionUpdateOne) SetDailyWindowStart(v time.Time) *BundleSubscriptionUpdateOne {
	_u.mutation.SetDailyWindowStart(v)
	return _u
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_u *BundleSubscriptionUpdateOne) SetNillableDailyWindowStart(v *time.Time) *BundleSubscriptionUpdateOne {
	if v != nil {
		_u.SetDailyWindowStart(*v)
	}
	return _u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (_u *BundleSubscriptionUpdateOne) ClearDailyWindowStart() *BundleSubscriptionUpdateOne {
	_u.mutation.ClearDailyWindowStart()
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *BundleSubscriptionUpdateOne) SetMonthlyWindowStart(v time.Time) *BundleSubscriptionUpdateOne {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *BundleSubscriptionUpdateOne) SetNillableMonthlyWindowStart(v *time.Time) *BundleSubscriptionUpdateOne {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (_u *BundleSubscriptionUpdateOne) ClearMonthlyWindowStart() *BundleSubscriptionUpdateOne {
	_u.mutation.ClearMonthlyWindowStart()
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *BundleSubscriptionUpdateOne) SetDailyUsageUsd(v float64) *BundleSubscriptionUpdateOne {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *BundleSubscriptionUpdateOne) SetNillableDailyUsageUsd(v *float64) *BundleSubscriptionUpdateOne {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *BundleSubscriptionUpdateOne) AddDailyUsageUsd(v float64) *BundleSubscriptionUpdateOne {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *BundleSubscriptionUpdateOne) SetMonthlyUsageUsd(v float64) *BundleSubscriptionUpdateOne {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *BundleSubscriptionUpdateOne) SetNillableMonthlyUsageUsd(v *float64) *BundleSubscriptionUpdateOne {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *BundleSubscriptionUpdateOne) AddMonthlyUsageUsd(v float64) *BundleSubscriptionUpdateOne {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *BundleSubscriptionUpdateOne) SetPaymentOrderID(v int64) *BundleSubscriptionUpdateOne {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *BundleSubscriptionUpdateOne) SetNillablePaymentOrderID(v *int64) *BundleSubscriptionUpdateOne {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *BundleSubscriptionUpdateOne) AddPaymentOrderID(v int64) *BundleSubscriptionUpdateOne {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (_u *BundleSubscriptionUpdateOne) ClearPaymentOrderID() *BundleSubscriptionUpdateOne {
	_u.mutation.ClearPaymentOrderID()
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *BundleSubscriptionUpdateOne) SetAssignedBy(v int64) *BundleSubscriptionUpdateOne {
	_u.mutation.ResetAssignedBy()
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *BundleSubscriptionUpdateOne) SetNillableAssignedBy(v *int64) *BundleSubscriptionUpdateOne {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// AddAssignedBy adds value to the "assigned_by" field.
func (_u *BundleSubscriptionUpdateOne) AddAssignedBy(v int64) *BundleSubscriptionUpdateOne {
	_u.mutation.AddAssignedBy(v)
	return _u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (_u *BundleSubscriptionUpdateOne) ClearAssignedBy() *BundleSubscriptionUpdateOne {
	_u.mutation.ClearAssignedBy()
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *BundleSubscriptionUpdateOne) SetAssignedAt(v time.Time) *BundleSubscriptionUpdateOne {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *BundleSubscriptionUpdateOne) SetNillableAssignedAt(v *time.Time) *BundleSubscriptionUpdateOne {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *BundleSubscriptionUpdateOne) SetNotes(v string) *BundleSubscriptionUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *BundleSubscriptionUpdateOne) SetNillableNotes(v *string) *BundleSubscriptionUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *BundleSubscriptionUpdateOne) ClearNotes() *BundleSubscriptionUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BundleSubscriptionUpdateOne) SetUpdatedAt(v time.Time) *BundleSubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BundleSubscriptionUpdateOne) SetUser(v *User) *BundleSubscriptionUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetPlanID sets the "plan" edge to the BundlePlan entity by ID.
func (_u *BundleSubscriptionUpdateOne) SetPlanID(id int64) *BundleSubscriptionUpdateOne {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the BundlePlan entity.
func (_u *BundleSubscriptionUpdateOne) SetPlan(v *BundlePlan) *BundleSubscriptionUpdateOne {
	return _u.SetPlanID(v.ID)
}

// AddEntitlementIDs adds the "entitlements" edge to the BundleSubscriptionEntitlement entity by IDs.
func (_u *BundleSubscriptionUpdateOne) AddEntitlementIDs(ids ...int64) *BundleSubscriptionUpdateOne {
	_u.mutation.AddEntitlementIDs(ids...)
	return _u
}

// AddEntitlements adds the "entitlements" edges to the BundleSubscriptionEntitlement entity.
func (_u *BundleSubscriptionUpdateOne) AddEntitlements(v ...*BundleSubscriptionEntitlement) *BundleSubscriptionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntitlementIDs(ids...)
}

// Mutation returns the BundleSubscriptionMutation object of the builder.
func (_u *BundleSubscriptionUpdateOne) Mutation() *BundleSubscriptionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BundleSubscriptionUpdateOne) ClearUser() *BundleSubscriptionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearPlan clears the "plan" edge to the BundlePlan entity.
func (_u *BundleSubscriptionUpdateOne) ClearPlan() *BundleSubscriptionUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// ClearEntitlements clears all "entitlements" edges to the BundleSubscriptionEntitlement entity.
func (_u *BundleSubscriptionUpdateOne) ClearEntitlements() *BundleSubscriptionUpdateOne {
	_u.mutation.ClearEntitlements()
	return _u
}

// RemoveEntitlementIDs removes the "entitlements" edge to BundleSubscriptionEntitlement entities by IDs.
func (_u *BundleSubscriptionUpdateOne) RemoveEntitlementIDs(ids ...int64) *BundleSubscriptionUpdateOne {
	_u.mutation.RemoveEntitlementIDs(ids...)
	return _u
}

// RemoveEntitlements removes "entitlements" edges to BundleSubscriptionEntitlement entities.
func (_u *BundleSubscriptionUpdateOne) RemoveEntitlements(v ...*BundleSubscriptionEntitlement) *BundleSubscriptionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntitlementIDs(ids...)
}

// Where appends a list predicates to the BundleSubscriptionUpdate builder.
func (_u *BundleSubscriptionUpdateOne) Where(ps ...predicate.BundleSubscription) *BundleSubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BundleSubscriptionUpdateOne) Select(field string, fields ...string) *BundleSubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BundleSubscription entity.
func (_u *BundleSubscriptionUpdateOne) Save(ctx context.Context) (*BundleSubscription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundleSubscriptionUpdateOne) SaveX(ctx context.Context) *BundleSubscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BundleSubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundleSubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BundleSubscriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bundlesubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BundleSubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := bundlesubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BundleSubscription.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleSubscription.user"`)
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleSubscription.plan"`)
	}
	return nil
}

func (_u *BundleSubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *BundleSubscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundlesubscription.Table, bundlesubscription.Columns, sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BundleSubscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bundlesubscription.FieldID)
		for _, f := range fields {
			if !bundlesubscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bundlesubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(bundlesubscription.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(bundlesubscription.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(bundlesubscription.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DailyWindowStart(); ok {
		_spec.SetField(bundlesubscription.FieldDailyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.DailyWindowStartCleared() {
		_spec.ClearField(bundlesubscription.FieldDailyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(bundlesubscription.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.MonthlyWindowStartCleared() {
		_spec.ClearField(bundlesubscription.FieldMonthlyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(bundlesubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(bundlesubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(bundlesubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(bundlesubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(bundlesubscription.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(bundlesubscription.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if _u.mutation.PaymentOrderIDCleared() {
		_spec.ClearField(bundlesubscription.FieldPaymentOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AssignedBy(); ok {
		_spec.SetField(bundlesubscription.FieldAssignedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAssignedBy(); ok {
		_spec.AddField(bundlesubscription.FieldAssignedBy, field.TypeInt64, value)
	}
	if _u.mutation.AssignedByCleared() {
		_spec.ClearField(bundlesubscription.FieldAssignedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(bundlesubscription.FieldAssignedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(bundlesubscription.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(bundlesubscription.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bundlesubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscription.UserTable,
			Columns: []string{bundlesubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscription.UserTable,
			Columns: []string{bundlesubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscription.PlanTable,
			Columns: []string{bundlesubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscription.PlanTable,
			Columns: []string{bundlesubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntitlementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundlesubscription.EntitlementsTable,
			Columns: []string{bundlesubscription.EntitlementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscriptionentitlement.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntitlementsIDs(); len(nodes) > 0 && !_u.mutation.EntitlementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundlesubscription.EntitlementsTable,
			Columns: []string{bundlesubscription.EntitlementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscriptionentitlement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntitlementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundlesubscription.EntitlementsTable,
			Columns: []string{bundlesubscription.EntitlementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscriptionentitlement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BundleSubscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundlesubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
