// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bundleplan"
	"github.com/Wei-Shaw/sub2api/ent/bundleplangroup"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscription"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BundlePlanUpdate is the builder for updating BundlePlan entities.
type BundlePlanUpdate struct {
	config
	hooks    []Hook
	mutation *BundlePlanMutation
}

// Where appends a list predicates to the BundlePlanUpdate builder.
func (_u *BundlePlanUpdate) Where(ps ...predicate.BundlePlan) *BundlePlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *BundlePlanUpdate) SetName(v string) *BundlePlanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BundlePlanUpdate) SetNillableName(v *string) *BundlePlanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BundlePlanUpdate) SetDescription(v string) *BundlePlanUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BundlePlanUpdate) SetNillableDescription(v *string) *BundlePlanUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *BundlePlanUpdate) SetProductName(v string) *BundlePlanUpdate {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *BundlePlanUpdate) SetNillableProductName(v *string) *BundlePlanUpdate {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *BundlePlanUpdate) SetPrice(v float64) *BundlePlanUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *BundlePlanUpdate) SetNillablePrice(v *float64) *BundlePlanUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *BundlePlanUpdate) AddPrice(v float64) *BundlePlanUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *BundlePlanUpdate) SetOriginalPrice(v float64) *BundlePlanUpdate {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *BundlePlanUpdate) SetNillableOriginalPrice(v *float64) *BundlePlanUpdate {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *BundlePlanUpdate) AddOriginalPrice(v float64) *BundlePlanUpdate {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (_u *BundlePlanUpdate) ClearOriginalPrice() *BundlePlanUpdate {
	_u.mutation.ClearOriginalPrice()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *BundlePlanUpdate) SetCurrency(v string) *BundlePlanUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *BundlePlanUpdate) SetNillableCurrency(v *string) *BundlePlanUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *BundlePlanUpdate) SetValidityDays(v int) *BundlePlanUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *BundlePlanUpdate) SetNillableValidityDays(v *int) *BundlePlanUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *BundlePlanUpdate) AddValidityDays(v int) *BundlePlanUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetValidityUnit sets the "validity_unit" field.
func (_u *BundlePlanUpdate) SetValidityUnit(v string) *BundlePlanUpdate {
	_u.mutation.SetValidityUnit(v)
	return _u
}

// SetNillableValidityUnit sets the "validity_unit" field if the given value is not nil.
func (_u *BundlePlanUpdate) SetNillableValidityUnit(v *string) *BundlePlanUpdate {
	if v != nil {
		_u.SetValidityUnit(*v)
	}
	return _u
}

// SetSharedDailyLimitUsd sets the "shared_daily_limit_usd" field.
func (_u *BundlePlanUpdate) SetSharedDailyLimitUsd(v float64) *BundlePlanUpdate {
	_u.mutation.ResetSharedDailyLimitUsd()
	_u.mutation.SetSharedDailyLimitUsd(v)
	return _u
}

// SetNillableSharedDailyLimitUsd sets the "shared_daily_limit_usd" field if the given value is not nil.
func (_u *BundlePlanUpdate) SetNillableSharedDailyLimitUsd(v *float64) *BundlePlanUpdate {
	if v != nil {
		_u.SetSharedDailyLimitUsd(*v)
	}
	return _u
}

// AddSharedDailyLimitUsd adds value to the "shared_daily_limit_usd" field.
func (_u *BundlePlanUpdate) AddSharedDailyLimitUsd(v float64) *BundlePlanUpdate {
	_u.mutation.AddSharedDailyLimitUsd(v)
	return _u
}

// ClearSharedDailyLimitUsd clears the value of the "shared_daily_limit_usd" field.
func (_u *BundlePlanUpdate) ClearSharedDailyLimitUsd() *BundlePlanUpdate {
	_u.mutation.ClearSharedDailyLimitUsd()
	return _u
}

// SetSharedMonthlyLimitUsd sets the "shared_monthly_limit_usd" field.
func (_u *BundlePlanUpdate) SetSharedMonthlyLimitUsd(v float64) *BundlePlanUpdate {
	_u.mutation.ResetSharedMonthlyLimitUsd()
	_u.mutation.SetSharedMonthlyLimitUsd(v)
	return _u
}

// SetNillableSharedMonthlyLimitUsd sets the "shared_monthly_limit_usd" field if the given value is not nil.
func (_u *BundlePlanUpdate) SetNillableSharedMonthlyLimitUsd(v *float64) *BundlePlanUpdate {
	if v != nil {
		_u.SetSharedMonthlyLimitUsd(*v)
	}
	return _u
}

// AddSharedMonthlyLimitUsd adds value to the "shared_monthly_limit_usd" field.
func (_u *BundlePlanUpdate) AddSharedMonthlyLimitUsd(v float64) *BundlePlanUpdate {
	_u.mutation.AddSharedMonthlyLimitUsd(v)
	return _u
}

// ClearSharedMonthlyLimitUsd clears the value of the "shared_monthly_limit_usd" field.
func (_u *BundlePlanUpdate) ClearSharedMonthlyLimitUsd() *BundlePlanUpdate {
	_u.mutation.ClearSharedMonthlyLimitUsd()
	return _u
}

// SetFeatures sets the "features" field.
func (_u *BundlePlanUpdate) SetFeatures(v string) *BundlePlanUpdate {
	_u.mutation.SetFeatures(v)
	return _u
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_u *BundlePlanUpdate) SetNillableFeatures(v *string) *BundlePlanUpdate {
	if v != nil {
		_u.SetFeatures(*v)
	}
	return _u
}

// SetForSale sets the "for_sale" field.
func (_u *BundlePlanUpdate) SetForSale(v bool) *BundlePlanUpdate {
	_u.mutation.SetForSale(v)
	return _u
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_u *BundlePlanUpdate) SetNillableForSale(v *bool) *BundlePlanUpdate {
	if v != nil {
		_u.SetForSale(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *BundlePlanUpdate) SetSortOrder(v int) *BundlePlanUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *BundlePlanUpdate) SetNillableSortOrder(v *int) *BundlePlanUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *BundlePlanUpdate) AddSortOrder(v int) *BundlePlanUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BundlePlanUpdate) SetUpdatedAt(v time.Time) *BundlePlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddGroupIDs adds the "groups" edge to the BundlePlanGroup entity by IDs.
func (_u *BundlePlanUpdate) AddGroupIDs(ids ...int64) *BundlePlanUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the BundlePlanGroup entity.
func (_u *BundlePlanUpdate) AddGroups(v ...*BundlePlanGroup) *BundlePlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the BundleSubscription entity by IDs.
func (_u *BundlePlanUpdate) AddSubscriptionIDs(ids ...int64) *BundlePlanUpdate {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the BundleSubscription entity.
func (_u *BundlePlanUpdate) AddSubscriptions(v ...*BundleSubscription) *BundlePlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// Mutation returns the BundlePlanMutation object of the builder.
func (_u *BundlePlanUpdate) Mutation() *BundlePlanMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the BundlePlanGroup entity.
func (_u *BundlePlanUpdate) ClearGroups() *BundlePlanUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to BundlePlanGroup entities by IDs.
func (_u *BundlePlanUpdate) RemoveGroupIDs(ids ...int64) *BundlePlanUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to BundlePlanGroup entities.
func (_u *BundlePlanUpdate) RemoveGroups(v ...*BundlePlanGroup) *BundlePlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearSubscriptions clears all "subscriptions" edges to the BundleSubscription entity.
func (_u *BundlePlanUpdate) ClearSubscriptions() *BundlePlanUpdate {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to BundleSubscription entities by IDs.
func (_u *BundlePlanUpdate) RemoveSubscriptionIDs(ids ...int64) *BundlePlanUpdate {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to BundleSubscription entities.
func (_u *BundlePlanUpdate) RemoveSubscriptions(v ...*BundleSubscription) *BundlePlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BundlePlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundlePlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BundlePlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundlePlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BundlePlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bundleplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BundlePlanUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := bundleplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BundlePlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := bundleplan.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "BundlePlan.product_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := bundleplan.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "BundlePlan.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidityUnit(); ok {
		if err := bundleplan.ValidityUnitValidator(v); err != nil {
			return &ValidationError{Name: "validity_unit", err: fmt.Errorf(`ent: validator failed for field "BundlePlan.validity_unit": %w`, err)}
		}
	}
	return nil
}

func (_u *BundlePlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundleplan.Table, bundleplan.Columns, sqlgraph.NewFieldSpec(bundleplan.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(bundleplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(bundleplan.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(bundleplan.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(bundleplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(bundleplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(bundleplan.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(bundleplan.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OriginalPriceCleared() {
		_spec.ClearField(bundleplan.FieldOriginalPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(bundleplan.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(bundleplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(bundleplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidityUnit(); ok {
		_spec.SetField(bundleplan.FieldValidityUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.SharedDailyLimitUsd(); ok {
		_spec.SetField(bundleplan.FieldSharedDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSharedDailyLimitUsd(); ok {
		_spec.AddField(bundleplan.FieldSharedDailyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.SharedDailyLimitUsdCleared() {
		_spec.ClearField(bundleplan.FieldSharedDailyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SharedMonthlyLimitUsd(); ok {
		_spec.SetField(bundleplan.FieldSharedMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSharedMonthlyLimitUsd(); ok {
		_spec.AddField(bundleplan.FieldSharedMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.SharedMonthlyLimitUsdCleared() {
		_spec.ClearField(bundleplan.FieldSharedMonthlyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(bundleplan.FieldFeatures, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForSale(); ok {
		_spec.SetField(bundleplan.FieldForSale, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(bundleplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(bundleplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bundleplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleplan.GroupsTable,
			Columns: []string{bundleplan.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplangroup.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleplan.GroupsTable,
			Columns: []string{bundleplan.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplangroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleplan.GroupsTable,
			Columns: []string{bundleplan.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplangroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleplan.SubscriptionsTable,
			Columns: []string{bundleplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleplan.SubscriptionsTable,
			Columns: []string{bundleplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleplan.SubscriptionsTable,
			Columns: []string{bundleplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundleplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BundlePlanUpdateOne is the builder for updating a single BundlePlan entity.
type BundlePlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BundlePlanMutation
}

// SetName sets the "name" field.
func (_u *BundlePlanUpdateOne) SetName(v string) *BundlePlanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BundlePlanUpdateOne) SetNillableName(v *string) *BundlePlanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BundlePlanUpdateOne) SetDescription(v string) *BundlePlanUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BundlePlanUpdateOne) SetNillableDescription(v *string) *BundlePlanUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *BundlePlanUpdateOne) SetProductName(v string) *BundlePlanUpdateOne {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *BundlePlanUpdateOne) SetNillableProductName(v *string) *BundlePlanUpdateOne {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *BundlePlanUpdateOne) SetPrice(v float64) *BundlePlanUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *BundlePlanUpdateOne) SetNillablePrice(v *float64) *BundlePlanUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *BundlePlanUpdateOne) AddPrice(v float64) *BundlePlanUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *BundlePlanUpdateOne) SetOriginalPrice(v float64) *BundlePlanUpdateOne {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *BundlePlanUpdateOne) SetNillableOriginalPrice(v *float64) *BundlePlanUpdateOne {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *BundlePlanUpdateOne) AddOriginalPrice(v float64) *BundlePlanUpdateOne {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (_u *BundlePlanUpdateOne) ClearOriginalPrice() *BundlePlanUpdateOne {
	_u.mutation.ClearOriginalPrice()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *BundlePlanUpdateOne) SetCurrency(v string) *BundlePlanUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *BundlePlanUpdateOne) SetNillableCurrency(v *string) *BundlePlanUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *BundlePlanUpdateOne) SetValidityDays(v int) *BundlePlanUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *BundlePlanUpdateOne) SetNillableValidityDays(v *int) *BundlePlanUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *BundlePlanUpdateOne) AddValidityDays(v int) *BundlePlanUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetValidityUnit sets the "validity_unit" field.
func (_u *BundlePlanUpdateOne) SetValidityUnit(v string) *BundlePlanUpdateOne {
	_u.mutation.SetValidityUnit(v)
	return _u
}

// SetNillableValidityUnit sets the "validity_unit" field if the given value is not nil.
func (_u *BundlePlanUpdateOne) SetNillableValidityUnit(v *string) *BundlePlanUpdateOne {
	if v != nil {
		_u.SetValidityUnit(*v)
	}
	return _u
}

// SetSharedDailyLimitUsd sets the "shared_daily_limit_usd" field.
func (_u *BundlePlanUpdateOne) SetSharedDailyLimitUsd(v float64) *BundlePlanUpdateOne {
	_u.mutation.ResetSharedDailyLimitUsd()
	_u.mutation.SetSharedDailyLimitUsd(v)
	return _u
}

// SetNillableSharedDailyLimitUsd sets the "shared_daily_limit_usd" field if the given value is not nil.
func (_u *BundlePlanUpdateOne) SetNillableSharedDailyLimitUsd(v *float64) *BundlePlanUpdateOne {
	if v != nil {
		_u.SetSharedDailyLimitUsd(*v)
	}
	return _u
}

// AddSharedDailyLimitUsd adds value to the "shared_daily_limit_usd" field.
func (_u *BundlePlanUpdateOne) AddSharedDailyLimitUsd(v float64) *BundlePlanUpdateOne {
	_u.mutation.AddSharedDailyLimitUsd(v)
	return _u
}

// ClearSharedDailyLimitUsd clears the value of the "shared_daily_limit_usd" field.
func (_u *BundlePlanUpdateOne) ClearSharedDailyLimitUsd() *BundlePlanUpdateOne {
	_u.mutation.ClearSharedDailyLimitUsd()
	return _u
}

// SetSharedMonthlyLimitUsd sets the "shared_monthly_limit_usd" field.
func (_u *BundlePlanUpdateOne) SetSharedMonthlyLimitUsd(v float64) *BundlePlanUpdateOne {
	_u.mutation.ResetSharedMonthlyLimitUsd()
	_u.mutation.SetSharedMonthlyLimitUsd(v)
	return _u
}

// SetNillableSharedMonthlyLimitUsd sets the "shared_monthly_limit_usd" field if the given value is not nil.
func (_u *BundlePlanUpdateOne) SetNillableSharedMonthlyLimitUsd(v *float64) *BundlePlanUpdateOne {
	if v != nil {
		_u.SetSharedMonthlyLimitUsd(*v)
	}
	return _u
}

// AddSharedMonthlyLimitUsd adds value to the "shared_monthly_limit_usd" field.
func (_u *BundlePlanUpdateOne) AddSharedMonthlyLimitUsd(v float64) *BundlePlanUpdateOne {
	_u.mutation.AddSharedMonthlyLimitUsd(v)
	return _u
}

// ClearSharedMonthlyLimitUsd clears the value of the "shared_monthly_limit_usd" field.
func (_u *BundlePlanUpdateOne) ClearSharedMonthlyLimitUsd() *BundlePlanUpdateOne {
	_u.mutation.ClearSharedMonthlyLimitUsd()
	return _u
}

// SetFeatures sets the "features" field.
func (_u *BundlePlanUpdateOne) SetFeatures(v string) *BundlePlanUpdateOne {
	_u.mutation.SetFeatures(v)
	return _u
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_u *BundlePlanUpdateOne) SetNillableFeatures(v *string) *BundlePlanUpdateOne {
	if v != nil {
		_u.SetFeatures(*v)
	}
	return _u
}

// SetForSale sets the "for_sale" field.
func (_u *BundlePlanUpdateOne) SetForSale(v bool) *BundlePlanUpdateOne {
	_u.mutation.SetForSale(v)
	return _u
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_u *BundlePlanUpdateOne) SetNillableForSale(v *bool) *BundlePlanUpdateOne {
	if v != nil {
		_u.SetForSale(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *BundlePlanUpdateOne) SetSortOrder(v int) *BundlePlanUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *BundlePlanUpdateOne) SetNillableSortOrder(v *int) *BundlePlanUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *BundlePlanUpdateOne) AddSortOrder(v int) *BundlePlanUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BundlePlanUpdateOne) SetUpdatedAt(v time.Time) *BundlePlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddGroupIDs adds the "groups" edge to the BundlePlanGroup entity by IDs.
func (_u *BundlePlanUpdateOne) AddGroupIDs(ids ...int64) *BundlePlanUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the BundlePlanGroup entity.
func (_u *BundlePlanUpdateOne) AddGroups(v ...*BundlePlanGroup) *BundlePlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the BundleSubscription entity by IDs.
func (_u *BundlePlanUpdateOne) AddSubscriptionIDs(ids ...int64) *BundlePlanUpdateOne {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the BundleSubscription entity.
func (_u *BundlePlanUpdateOne) AddSubscriptions(v ...*BundleSubscription) *BundlePlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// Mutation returns the BundlePlanMutation object of the builder.
func (_u *BundlePlanUpdateOne) Mutation() *BundlePlanMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the BundlePlanGroup entity.
func (_u *BundlePlanUpdateOne) ClearGroups() *BundlePlanUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to BundlePlanGroup entities by IDs.
func (_u *BundlePlanUpdateOne) RemoveGroupIDs(ids ...int64) *BundlePlanUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to BundlePlanGroup entities.
func (_u *BundlePlanUpdateOne) RemoveGroups(v ...*BundlePlanGroup) *BundlePlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearSubscriptions clears all "subscriptions" edges to the BundleSubscription entity.
func (_u *BundlePlanUpdateOne) ClearSubscriptions() *BundlePlanUpdateOne {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to BundleSubscription entities by IDs.
func (_u *BundlePlanUpdateOne) RemoveSubscriptionIDs(ids ...int64) *BundlePlanUpdateOne {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to BundleSubscription entities.
func (_u *BundlePlanUpdateOne) RemoveSubscriptions(v ...*BundleSubscription) *BundlePlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// Where appends a list predicates to the BundlePlanUpdate builder.
func (_u *BundlePlanUpdateOne) Where(ps ...predicate.BundlePlan) *BundlePlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BundlePlanUpdateOne) Select(field string, fields ...string) *BundlePlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BundlePlan entity.
func (_u *BundlePlanUpdateOne) Save(ctx context.Context) (*BundlePlan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundlePlanUpdateOne) SaveX(ctx context.Context) *BundlePlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BundlePlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundlePlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BundlePlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bundleplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BundlePlanUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := bundleplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BundlePlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := bundleplan.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "BundlePlan.product_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := bundleplan.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "BundlePlan.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidityUnit(); ok {
		if err := bundleplan.ValidityUnitValidator(v); err != nil {
			return &ValidationError{Name: "validity_unit", err: fmt.Errorf(`ent: validator failed for field "BundlePlan.validity_unit": %w`, err)}
		}
	}
	return nil
}

func (_u *BundlePlanUpdateOne) sqlSave(ctx context.Context) (_node *BundlePlan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundleplan.Table, bundleplan.Columns, sqlgraph.NewFieldSpec(bundleplan.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BundlePlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bundleplan.FieldID)
		for _, f := range fields {
			if !bundleplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bundleplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(bundleplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(bundleplan.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(bundleplan.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(bundleplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(bundleplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(bundleplan.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(bundleplan.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OriginalPriceCleared() {
		_spec.ClearField(bundleplan.FieldOriginalPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(bundleplan.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(bundleplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(bundleplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidityUnit(); ok {
		_spec.SetField(bundleplan.FieldValidityUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.SharedDailyLimitUsd(); ok {
		_spec.SetField(bundleplan.FieldSharedDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSharedDailyLimitUsd(); ok {
		_spec.AddField(bundleplan.FieldSharedDailyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.SharedDailyLimitUsdCleared() {
		_spec.ClearField(bundleplan.FieldSharedDailyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SharedMonthlyLimitUsd(); ok {
		_spec.SetField(bundleplan.FieldSharedMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSharedMonthlyLimitUsd(); ok {
		_spec.AddField(bundleplan.FieldSharedMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.SharedMonthlyLimitUsdCleared() {
		_spec.ClearField(bundleplan.FieldSharedMonthlyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(bundleplan.FieldFeatures, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForSale(); ok {
		_spec.SetField(bundleplan.FieldForSale, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(bundleplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(bundleplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bundleplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleplan.GroupsTable,
			Columns: []string{bundleplan.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplangroup.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleplan.GroupsTable,
			Columns: []string{bundleplan.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplangroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleplan.GroupsTable,
			Columns: []string{bundleplan.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplangroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleplan.SubscriptionsTable,
			Columns: []string{bundleplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleplan.SubscriptionsTable,
			Columns: []string{bundleplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleplan.SubscriptionsTable,
			Columns: []string{bundleplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BundlePlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundleplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
