// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bundleplan"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscription"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscriptionentitlement"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// BundleSubscriptionCreate is the builder for creating a BundleSubscription entity.
type BundleSubscriptionCreate struct {
	config
	mutation *BundleSubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *BundleSubscriptionCreate) SetUserID(v int64) *BundleSubscriptionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetBundlePlanID sets the "bundle_plan_id" field.
func (_c *BundleSubscriptionCreate) SetBundlePlanID(v int64) *BundleSubscriptionCreate {
	_c.mutation.SetBundlePlanID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *BundleSubscriptionCreate) SetStatus(v string) *BundleSubscriptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BundleSubscriptionCreate) SetNillableStatus(v *string) *BundleSubscriptionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *BundleSubscriptionCreate) SetStartsAt(v time.Time) *BundleSubscriptionCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *BundleSubscriptionCreate) SetExpiresAt(v time.Time) *BundleSubscriptionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_c *BundleSubscriptionCreate) SetDailyWindowStart(v time.Time) *BundleSubscriptionCreate {
	_c.mutation.SetDailyWindowStart(v)
	return _c
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_c *BundleSubscriptionCreate) SetNillableDailyWindowStart(v *time.Time) *BundleSubscriptionCreate {
	if v != nil {
		_c.SetDailyWindowStart(*v)
	}
	return _c
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_c *BundleSubscriptionCreate) SetMonthlyWindowStart(v time.Time) *BundleSubscriptionCreate {
	_c.mutation.SetMonthlyWindowStart(v)
	return _c
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_c *BundleSubscriptionCreate) SetNillableMonthlyWindowStart(v *time.Time) *BundleSubscriptionCreate {
	if v != nil {
		_c.SetMonthlyWindowStart(*v)
	}
	return _c
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_c *BundleSubscriptionCreate) SetDailyUsageUsd(v float64) *BundleSubscriptionCreate {
	_c.mutation.SetDailyUsageUsd(v)
	return _c
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_c *BundleSubscriptionCreate) SetNillableDailyUsageUsd(v *float64) *BundleSubscriptionCreate {
	if v != nil {
		_c.SetDailyUsageUsd(*v)
	}
	return _c
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_c *BundleSubscriptionCreate) SetMonthlyUsageUsd(v float64) *BundleSubscriptionCreate {
	_c.mutation.SetMonthlyUsageUsd(v)
	return _c
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_c *BundleSubscriptionCreate) SetNillableMonthlyUsageUsd(v *float64) *BundleSubscriptionCreate {
	if v != nil {
		_c.SetMonthlyUsageUsd(*v)
	}
	return _c
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_c *BundleSubscriptionCreate) SetPaymentOrderID(v int64) *BundleSubscriptionCreate {
	_c.mutation.SetPaymentOrderID(v)
	return _c
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_c *BundleSubscriptionCreate) SetNillablePaymentOrderID(v *int64) *BundleSubscriptionCreate {
	if v != nil {
		_c.SetPaymentOrderID(*v)
	}
	return _c
}

// SetAssignedBy sets the "assigned_by" field.
func (_c *BundleSubscriptionCreate) SetAssignedBy(v int64) *BundleSubscriptionCreate {
	_c.mutation.SetAssignedBy(v)
	return _c
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_c *BundleSubscriptionCreate) SetNillableAssignedBy(v *int64) *BundleSubscriptionCreate {
	if v != nil {
		_c.SetAssignedBy(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *BundleSubscriptionCreate) SetAssignedAt(v time.Time) *BundleSubscriptionCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *BundleSubscriptionCreate) SetNillableAssignedAt(v *time.Time) *BundleSubscriptionCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *BundleSubscriptionCreate) SetNotes(v string) *BundleSubscriptionCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *BundleSubscriptionCreate) SetNillableNotes(v *string) *BundleSubscriptionCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BundleSubscriptionCreate) SetCreatedAt(v time.Time) *BundleSubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BundleSubscriptionCreate) SetNillableCreatedAt(v *time.Time) *BundleSubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BundleSubscriptionCreate) SetUpdatedAt(v time.Time) *BundleSubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BundleSubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *BundleSubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *BundleSubscriptionCreate) SetUser(v *User) *BundleSubscriptionCreate {
	return _c.SetUserID(v.ID)
}

// SetPlanID sets the "plan" edge to the BundlePlan entity by ID.
func (_c *BundleSubscriptionCreate) SetPlanID(id int64) *BundleSubscriptionCreate {
	_c.mutation.SetPlanID(id)
	return _c
}

// SetPlan sets the "plan" edge to the BundlePlan entity.
func (_c *BundleSubscriptionCreate) SetPlan(v *BundlePlan) *BundleSubscriptionCreate {
	return _c.SetPlanID(v.ID)
}

// AddEntitlementIDs adds the "entitlements" edge to the BundleSubscriptionEntitlement entity by IDs.
func (_c *BundleSubscriptionCreate) AddEntitlementIDs(ids ...int64) *BundleSubscriptionCreate {
	_c.mutation.AddEntitlementIDs(ids...)
	return _c
}

// AddEntitlements adds the "entitlements" edges to the BundleSubscriptionEntitlement entity.
func (_c *BundleSubscriptionCreate) AddEntitlements(v ...*BundleSubscriptionEntitlement) *BundleSubscriptionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEntitlementIDs(ids...)
}

// Mutation returns the BundleSubscriptionMutation object of the builder.
func (_c *BundleSubscriptionCreate) Mutation() *BundleSubscriptionMutation {
	return _c.mutation
}

// Save creates the BundleSubscription in the database.
func (_c *BundleSubscriptionCreate) Save(ctx context.Context) (*BundleSubscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BundleSubscriptionCreate) SaveX(ctx context.Context) *BundleSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BundleSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BundleSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BundleSubscriptionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := bundlesubscription.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		v := bundlesubscription.DefaultDailyUsageUsd
		_c.mutation.SetDailyUsageUsd(v)
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		v := bundlesubscription.DefaultMonthlyUsageUsd
		_c.mutation.SetMonthlyUsageUsd(v)
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		v := bundlesubscription.DefaultAssignedAt()
		_c.mutation.SetAssignedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := bundlesubscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := bundlesubscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BundleSubscriptionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "BundleSubscription.user_id"`)}
	}
	if _, ok := _c.mutation.BundlePlanID(); !ok {
		return &ValidationError{Name: "bundle_plan_id", err: errors.New(`ent: missing required field "BundleSubscription.bundle_plan_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BundleSubscription.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := bundlesubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BundleSubscription.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "BundleSubscription.starts_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "BundleSubscription.expires_at"`)}
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		return &ValidationError{Name: "daily_usage_usd", err: errors.New(`ent: missing required field "BundleSubscription.daily_usage_usd"`)}
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		return &ValidationError{Name: "monthly_usage_usd", err: errors.New(`ent: missing required field "BundleSubscription.monthly_usage_usd"`)}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "BundleSubscription.assigned_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BundleSubscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BundleSubscription.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "BundleSubscription.user"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "BundleSubscription.plan"`)}
	}
	return nil
}

func (_c *BundleSubscriptionCreate) sqlSave(ctx context.Context) (*BundleSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BundleSubscriptionCreate) createSpec() (*BundleSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &BundleSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bundlesubscription.Table, sqlgraph.NewFieldSpec(bundlesubscription.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(bundlesubscription.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(bundlesubscription.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(bundlesubscription.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.DailyWindowStart(); ok {
		_spec.SetField(bundlesubscription.FieldDailyWindowStart, field.TypeTime, value)
		_node.DailyWindowStart = &value
	}
	if value, ok := _c.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(bundlesubscription.FieldMonthlyWindowStart, field.TypeTime, value)
		_node.MonthlyWindowStart = &value
	}
	if value, ok := _c.mutation.DailyUsageUsd(); ok {
		_spec.SetField(bundlesubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
		_node.DailyUsageUsd = value
	}
	if value, ok := _c.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(bundlesubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
		_node.MonthlyUsageUsd = value
	}
	if value, ok := _c.mutation.PaymentOrderID(); ok {
		_spec.SetField(bundlesubscription.FieldPaymentOrderID, field.TypeInt64, value)
		_node.PaymentOrderID = &value
	}
	if value, ok := _c.mutation.AssignedBy(); ok {
		_spec.SetField(bundlesubscription.FieldAssignedBy, field.TypeInt64, value)
		_node.AssignedBy = &value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(bundlesubscription.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(bundlesubscription.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(bundlesubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(bundlesubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscription.UserTable,
			Columns: []string{bundlesubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlesubscription.PlanTable,
			Columns: []string{bundlesubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BundlePlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EntitlementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundlesubscription.EntitlementsTable,
			Columns: []string{bundlesubscription.EntitlementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlesubscriptionentitlement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BundleSubscription.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BundleSubscriptionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *BundleSubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *BundleSubscriptionUpsertOne {
	_c.conflict = opts
	return &BundleSubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BundleSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BundleSubscriptionCreate) OnConflictColumns(columns ...string) *BundleSubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BundleSubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// BundleSubscriptionUpsertOne is the builder for "upsert"-ing
	//  one BundleSubscription node.
	BundleSubscriptionUpsertOne struct {
		create *BundleSubscriptionCreate
	}

	// BundleSubscriptionUpsert is the "OnConflict" setter.
	BundleSubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *BundleSubscriptionUpsert) SetUserID(v int64) *BundleSubscriptionUpsert {
	u.Set(bundlesubscription.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BundleSubscriptionUpsert) UpdateUserID() *BundleSubscriptionUpsert {
	u.SetExcluded(bundlesubscription.FieldUserID)
	return u
}

// SetBundlePlanID sets the "bundle_plan_id" field.
func (u *BundleSubscriptionUpsert) SetBundlePlanID(v int64) *BundleSubscriptionUpsert {
	u.Set(bundlesubscription.FieldBundlePlanID, v)
	return u
}

// UpdateBundlePlanID sets the "bundle_plan_id" field to the value that was provided on create.
func (u *BundleSubscriptionUpsert) UpdateBundlePlanID() *BundleSubscriptionUpsert {
	u.SetExcluded(bundlesubscription.FieldBundlePlanID)
	return u
}

// SetStatus sets the "status" field.
func (u *BundleSubscriptionUpsert) SetStatus(v string) *BundleSubscriptionUpsert {
	u.Set(bundlesubscription.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BundleSubscriptionUpsert) UpdateStatus() *BundleSubscriptionUpsert {
	u.SetExcluded(bundlesubscription.FieldStatus)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *BundleSubscriptionUpsert) SetStartsAt(v time.Time) *BundleSubscriptionUpsert {
	u.Set(bundlesubscription.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *BundleSubscriptionUpsert) UpdateStartsAt() *BundleSubscriptionUpsert {
	u.SetExcluded(bundlesubscription.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *BundleSubscriptionUpsert) SetExpiresAt(v time.Time) *BundleSubscriptionUpsert {
	u.Set(bundlesubscription.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *BundleSubscriptionUpsert) UpdateExpiresAt() *BundleSubscriptionUpsert {
	u.SetExcluded(bundlesubscription.FieldExpiresAt)
	return u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *BundleSubscriptionUpsert) SetDailyWindowStart(v time.Time) *BundleSubscriptionUpsert {
	u.Set(bundlesubscription.FieldDailyWindowStart, v)
	return u
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *BundleSubscriptionUpsert) UpdateDailyWindowStart() *BundleSubscriptionUpsert {
	u.SetExcluded(bundlesubscription.FieldDailyWindowStart)
	return u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *BundleSubscriptionUpsert) ClearDailyWindowStart() *BundleSubscriptionUpsert {
	u.SetNull(bundlesubscription.FieldDailyWindowStart)
	return u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *BundleSubscriptionUpsert) SetMonthlyWindowStart(v time.Time) *BundleSubscriptionUpsert {
	u.Set(bundlesubscription.FieldMonthlyWindowStart, v)
	return u
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *BundleSubscriptionUpsert) UpdateMonthlyWindowStart() *BundleSubscriptionUpsert {
	u.SetExcluded(bundlesubscription.FieldMonthlyWindowStart)
	return u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *BundleSubscriptionUpsert) ClearMonthlyWindowStart() *BundleSubscriptionUpsert {
	u.SetNull(bundlesubscription.FieldMonthlyWindowStart)
	return u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *BundleSubscriptionUpsert) SetDailyUsageUsd(v float64) *BundleSubscriptionUpsert {
	u.Set(bundlesubscription.FieldDailyUsageUsd, v)
	return u
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *BundleSubscriptionUpsert) UpdateDailyUsageUsd() *BundleSubscriptionUpsert {
	u.SetExcluded(bundlesubscription.FieldDailyUsageUsd)
	return u
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *BundleSubscriptionUpsert) AddDailyUsageUsd(v float64) *BundleSubscriptionUpsert {
	u.Add(bundlesubscription.FieldDailyUsageUsd, v)
	return u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *BundleSubscriptionUpsert) SetMonthlyUsageUsd(v float64) *BundleSubscriptionUpsert {
	u.Set(bundlesubscription.FieldMonthlyUsageUsd, v)
	return u
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *BundleSubscriptionUpsert) UpdateMonthlyUsageUsd() *BundleSubscriptionUpsert {
	u.SetExcluded(bundlesubscription.FieldMonthlyUsageUsd)
	return u
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *BundleSubscriptionUpsert) AddMonthlyUsageUsd(v float64) *BundleSubscriptionUpsert {
	u.Add(bundlesubscription.FieldMonthlyUsageUsd, v)
	return u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *BundleSubscriptionUpsert) SetPaymentOrderID(v int64) *BundleSubscriptionUpsert {
	u.Set(bundlesubscription.FieldPaymentOrderID, v)
	return u
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *BundleSubscriptionUpsert) UpdatePaymentOrderID() *BundleSubscriptionUpsert {
	u.SetExcluded(bundlesubscription.FieldPaymentOrderID)
	return u
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *BundleSubscriptionUpsert) AddPaymentOrderID(v int64) *BundleSubscriptionUpsert {
	u.Add(bundlesubscription.FieldPaymentOrderID, v)
	return u
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *BundleSubscriptionUpsert) ClearPaymentOrderID() *BundleSubscriptionUpsert {
	u.SetNull(bundlesubscription.FieldPaymentOrderID)
	return u
}

// SetAssignedBy sets the "assigned_by" field.
func (u *BundleSubscriptionUpsert) SetAssignedBy(v int64) *BundleSubscriptionUpsert {
	u.Set(bundlesubscription.FieldAssignedBy, v)
	return u
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *BundleSubscriptionUpsert) UpdateAssignedBy() *BundleSubscriptionUpsert {
	u.SetExcluded(bundlesubscription.FieldAssignedBy)
	return u
}

// AddAssignedBy adds v to the "assigned_by" field.
func (u *BundleSubscriptionUpsert) AddAssignedBy(v int64) *BundleSubscriptionUpsert {
	u.Add(bundlesubscription.FieldAssignedBy, v)
	return u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *BundleSubscriptionUpsert) ClearAssignedBy() *BundleSubscriptionUpsert {
	u.SetNull(bundlesubscription.FieldAssignedBy)
	return u
}

// SetAssignedAt sets the "assigned_at" field.
func (u *BundleSubscriptionUpsert) SetAssignedAt(v time.Time) *BundleSubscriptionUpsert {
	u.Set(bundlesubscription.FieldAssignedAt, v)
	return u
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *BundleSubscriptionUpsert) UpdateAssignedAt() *BundleSubscriptionUpsert {
	u.SetExcluded(bundlesubscription.FieldAssignedAt)
	return u
}

// SetNotes sets the "notes" field.
func (u *BundleSubscriptionUpsert) SetNotes(v string) *BundleSubscriptionUpsert {
	u.Set(bundlesubscription.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *BundleSubscriptionUpsert) UpdateNotes() *BundleSubscriptionUpsert {
	u.SetExcluded(bundlesubscription.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *BundleSubscriptionUpsert) ClearNotes() *BundleSubscriptionUpsert {
	u.SetNull(bundlesubscription.FieldNotes)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BundleSubscriptionUpsert) SetUpdatedAt(v time.Time) *BundleSubscriptionUpsert {
	u.Set(bundlesubscription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BundleSubscriptionUpsert) UpdateUpdatedAt() *BundleSubscriptionUpsert {
	u.SetExcluded(bundlesubscription.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BundleSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BundleSubscriptionUpsertOne) UpdateNewValues() *BundleSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(bundlesubscription.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BundleSubscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BundleSubscriptionUpsertOne) Ignore() *BundleSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BundleSubscriptionUpsertOne) DoNothing() *BundleSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BundleSubscriptionCreate.OnConflict
// documentation for more info.
func (u *BundleSubscriptionUpsertOne) Update(set func(*BundleSubscriptionUpsert)) *BundleSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BundleSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *BundleSubscriptionUpsertOne) SetUserID(v int64) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertOne) UpdateUserID() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateUserID()
	})
}

// SetBundlePlanID sets the "bundle_plan_id" field.
func (u *BundleSubscriptionUpsertOne) SetBundlePlanID(v int64) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetBundlePlanID(v)
	})
}

// UpdateBundlePlanID sets the "bundle_plan_id" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertOne) UpdateBundlePlanID() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateBundlePlanID()
	})
}

// SetStatus sets the "status" field.
func (u *BundleSubscriptionUpsertOne) SetStatus(v string) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertOne) UpdateStatus() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *BundleSubscriptionUpsertOne) SetStartsAt(v time.Time) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertOne) UpdateStartsAt() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *BundleSubscriptionUpsertOne) SetExpiresAt(v time.Time) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertOne) UpdateExpiresAt() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *BundleSubscriptionUpsertOne) SetDailyWindowStart(v time.Time) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertOne) UpdateDailyWindowStart() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *BundleSubscriptionUpsertOne) ClearDailyWindowStart() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *BundleSubscriptionUpsertOne) SetMonthlyWindowStart(v time.Time) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertOne) UpdateMonthlyWindowStart() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *BundleSubscriptionUpsertOne) ClearMonthlyWindowStart() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *BundleSubscriptionUpsertOne) SetDailyUsageUsd(v float64) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *BundleSubscriptionUpsertOne) AddDailyUsageUsd(v float64) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertOne) UpdateDailyUsageUsd() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *BundleSubscriptionUpsertOne) SetMonthlyUsageUsd(v float64) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *BundleSubscriptionUpsertOne) AddMonthlyUsageUsd(v float64) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertOne) UpdateMonthlyUsageUsd() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *BundleSubscriptionUpsertOne) SetPaymentOrderID(v int64) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *BundleSubscriptionUpsertOne) AddPaymentOrderID(v int64) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertOne) UpdatePaymentOrderID() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *BundleSubscriptionUpsertOne) ClearPaymentOrderID() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.ClearPaymentOrderID()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *BundleSubscriptionUpsertOne) SetAssignedBy(v int64) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetAssignedBy(v)
	})
}

// AddAssignedBy adds v to the "assigned_by" field.
func (u *BundleSubscriptionUpsertOne) AddAssignedBy(v int64) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.AddAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertOne) UpdateAssignedBy() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateAssignedBy()
	})
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *BundleSubscriptionUpsertOne) ClearAssignedBy() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.ClearAssignedBy()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *BundleSubscriptionUpsertOne) SetAssignedAt(v time.Time) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertOne) UpdateAssignedAt() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateAssignedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *BundleSubscriptionUpsertOne) SetNotes(v string) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertOne) UpdateNotes() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *BundleSubscriptionUpsertOne) ClearNotes() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BundleSubscriptionUpsertOne) SetUpdatedAt(v time.Time) *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertOne) UpdateUpdatedAt() *BundleSubscriptionUpsertOne {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BundleSubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BundleSubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BundleSubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BundleSubscriptionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BundleSubscriptionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BundleSubscriptionCreateBulk is the builder for creating many BundleSubscription entities in bulk.
type BundleSubscriptionCreateBulk struct {
	config
	err      error
	builders []*BundleSubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the BundleSubscription entities in the database.
func (_c *BundleSubscriptionCreateBulk) Save(ctx context.Context) ([]*BundleSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BundleSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BundleSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BundleSubscriptionCreateBulk) SaveX(ctx context.Context) []*BundleSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BundleSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BundleSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BundleSubscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BundleSubscriptionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *BundleSubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *BundleSubscriptionUpsertBulk {
	_c.conflict = opts
	return &BundleSubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BundleSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BundleSubscriptionCreateBulk) OnConflictColumns(columns ...string) *BundleSubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BundleSubscriptionUpsertBulk{
		create: _c,
	}
}

// BundleSubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of BundleSubscription nodes.
type BundleSubscriptionUpsertBulk struct {
	create *BundleSubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BundleSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BundleSubscriptionUpsertBulk) UpdateNewValues() *BundleSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(bundlesubscription.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BundleSubscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BundleSubscriptionUpsertBulk) Ignore() *BundleSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BundleSubscriptionUpsertBulk) DoNothing() *BundleSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BundleSubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *BundleSubscriptionUpsertBulk) Update(set func(*BundleSubscriptionUpsert)) *BundleSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BundleSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *BundleSubscriptionUpsertBulk) SetUserID(v int64) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertBulk) UpdateUserID() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateUserID()
	})
}

// SetBundlePlanID sets the "bundle_plan_id" field.
func (u *BundleSubscriptionUpsertBulk) SetBundlePlanID(v int64) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetBundlePlanID(v)
	})
}

// UpdateBundlePlanID sets the "bundle_plan_id" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertBulk) UpdateBundlePlanID() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateBundlePlanID()
	})
}

// SetStatus sets the "status" field.
func (u *BundleSubscriptionUpsertBulk) SetStatus(v string) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertBulk) UpdateStatus() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *BundleSubscriptionUpsertBulk) SetStartsAt(v time.Time) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertBulk) UpdateStartsAt() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *BundleSubscriptionUpsertBulk) SetExpiresAt(v time.Time) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertBulk) UpdateExpiresAt() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *BundleSubscriptionUpsertBulk) SetDailyWindowStart(v time.Time) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertBulk) UpdateDailyWindowStart() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *BundleSubscriptionUpsertBulk) ClearDailyWindowStart() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *BundleSubscriptionUpsertBulk) SetMonthlyWindowStart(v time.Time) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertBulk) UpdateMonthlyWindowStart() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *BundleSubscriptionUpsertBulk) ClearMonthlyWindowStart() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *BundleSubscriptionUpsertBulk) SetDailyUsageUsd(v float64) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *BundleSubscriptionUpsertBulk) AddDailyUsageUsd(v float64) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertBulk) UpdateDailyUsageUsd() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *BundleSubscriptionUpsertBulk) SetMonthlyUsageUsd(v float64) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *BundleSubscriptionUpsertBulk) AddMonthlyUsageUsd(v float64) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertBulk) UpdateMonthlyUsageUsd() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *BundleSubscriptionUpsertBulk) SetPaymentOrderID(v int64) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *BundleSubscriptionUpsertBulk) AddPaymentOrderID(v int64) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertBulk) UpdatePaymentOrderID() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *BundleSubscriptionUpsertBulk) ClearPaymentOrderID() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.ClearPaymentOrderID()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *BundleSubscriptionUpsertBulk) SetAssignedBy(v int64) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetAssignedBy(v)
	})
}

// AddAssignedBy adds v to the "assigned_by" field.
func (u *BundleSubscriptionUpsertBulk) AddAssignedBy(v int64) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.AddAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertBulk) UpdateAssignedBy() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateAssignedBy()
	})
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *BundleSubscriptionUpsertBulk) ClearAssignedBy() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.ClearAssignedBy()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *BundleSubscriptionUpsertBulk) SetAssignedAt(v time.Time) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertBulk) UpdateAssignedAt() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateAssignedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *BundleSubscriptionUpsertBulk) SetNotes(v string) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertBulk) UpdateNotes() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *BundleSubscriptionUpsertBulk) ClearNotes() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BundleSubscriptionUpsertBulk) SetUpdatedAt(v time.Time) *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BundleSubscriptionUpsertBulk) UpdateUpdatedAt() *BundleSubscriptionUpsertBulk {
	return u.Update(func(s *BundleSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BundleSubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BundleSubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BundleSubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BundleSubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
