// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscriptionentitlement"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BundleSubscriptionEntitlementDelete is the builder for deleting a BundleSubscriptionEntitlement entity.
type BundleSubscriptionEntitlementDelete struct {
	config
	hooks    []Hook
	mutation *BundleSubscriptionEntitlementMutation
}

// Where appends a list predicates to the BundleSubscriptionEntitlementDelete builder.
func (_d *BundleSubscriptionEntitlementDelete) Where(ps ...predicate.BundleSubscriptionEntitlement) *BundleSubscriptionEntitlementDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BundleSubscriptionEntitlementDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BundleSubscriptionEntitlementDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BundleSubscriptionEntitlementDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(bundlesubscriptionentitlement.Table, sqlgraph.NewFieldSpec(bundlesubscriptionentitlement.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BundleSubscriptionEntitlementDeleteOne is the builder for deleting a single BundleSubscriptionEntitlement entity.
type BundleSubscriptionEntitlementDeleteOne struct {
	_d *BundleSubscriptionEntitlementDelete
}

// Where appends a list predicates to the BundleSubscriptionEntitlementDelete builder.
func (_d *BundleSubscriptionEntitlementDeleteOne) Where(ps ...predicate.BundleSubscriptionEntitlement) *BundleSubscriptionEntitlementDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BundleSubscriptionEntitlementDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bundlesubscriptionentitlement.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BundleSubscriptionEntitlementDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
