// Code generated by ent, DO NOT EDIT.

package bundlesubscriptionentitlement

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the bundlesubscriptionentitlement type in the database.
	Label = "bundle_subscription_entitlement"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBundleSubscriptionID holds the string denoting the bundle_subscription_id field in the database.
	FieldBundleSubscriptionID = "bundle_subscription_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldDailyLimitUsd holds the string denoting the daily_limit_usd field in the database.
	FieldDailyLimitUsd = "daily_limit_usd"
	// FieldMonthlyLimitUsd holds the string denoting the monthly_limit_usd field in the database.
	FieldMonthlyLimitUsd = "monthly_limit_usd"
	// FieldDailyUsageUsd holds the string denoting the daily_usage_usd field in the database.
	FieldDailyUsageUsd = "daily_usage_usd"
	// FieldMonthlyUsageUsd holds the string denoting the monthly_usage_usd field in the database.
	FieldMonthlyUsageUsd = "monthly_usage_usd"
	// EdgeSubscription holds the string denoting the subscription edge name in mutations.
	EdgeSubscription = "subscription"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// Table holds the table name of the bundlesubscriptionentitlement in the database.
	Table = "bundle_subscription_entitlements"
	// SubscriptionTable is the table that holds the subscription relation/edge.
	SubscriptionTable = "bundle_subscription_entitlements"
	// SubscriptionInverseTable is the table name for the BundleSubscription entity.
	// It exists in this package in order to avoid circular dependency with the "bundlesubscription" package.
	SubscriptionInverseTable = "bundle_subscriptions"
	// SubscriptionColumn is the table column denoting the subscription relation/edge.
	SubscriptionColumn = "bundle_subscription_id"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "bundle_subscription_entitlements"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
)

// Columns holds all SQL columns for bundlesubscriptionentitlement fields.
var Columns = []string{
	FieldID,
	FieldBundleSubscriptionID,
	FieldGroupID,
	FieldPlatform,
	FieldDailyLimitUsd,
	FieldMonthlyLimitUsd,
	FieldDailyUsageUsd,
	FieldMonthlyUsageUsd,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultDailyUsageUsd holds the default value on creation for the "daily_usage_usd" field.
	DefaultDailyUsageUsd float64
	// DefaultMonthlyUsageUsd holds the default value on creation for the "monthly_usage_usd" field.
	DefaultMonthlyUsageUsd float64
)

// OrderOption defines the ordering options for the BundleSubscriptionEntitlement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBundleSubscriptionID orders the results by the bundle_subscription_id field.
func ByBundleSubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBundleSubscriptionID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByDailyLimitUsd orders the results by the daily_limit_usd field.
func ByDailyLimitUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyLimitUsd, opts...).ToFunc()
}

// ByMonthlyLimitUsd orders the results by the monthly_limit_usd field.
func ByMonthlyLimitUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyLimitUsd, opts...).ToFunc()
}

// ByDailyUsageUsd orders the results by the daily_usage_usd field.
func ByDailyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyUsageUsd, opts...).ToFunc()
}

// ByMonthlyUsageUsd orders the results by the monthly_usage_usd field.
func ByMonthlyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyUsageUsd, opts...).ToFunc()
}

// BySubscriptionField orders the results by subscription field.
func BySubscriptionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubscriptionStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newSubscriptionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubscriptionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
