// Code generated by ent, DO NOT EDIT.

package bundlesubscriptionentitlement

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldLTE(FieldID, id))
}

// BundleSubscriptionID applies equality check predicate on the "bundle_subscription_id" field. It's identical to BundleSubscriptionIDEQ.
func BundleSubscriptionID(v int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldBundleSubscriptionID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldGroupID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldPlatform, v))
}

// DailyLimitUsd applies equality check predicate on the "daily_limit_usd" field. It's identical to DailyLimitUsdEQ.
func DailyLimitUsd(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldDailyLimitUsd, v))
}

// MonthlyLimitUsd applies equality check predicate on the "monthly_limit_usd" field. It's identical to MonthlyLimitUsdEQ.
func MonthlyLimitUsd(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldMonthlyLimitUsd, v))
}

// DailyUsageUsd applies equality check predicate on the "daily_usage_usd" field. It's identical to DailyUsageUsdEQ.
func DailyUsageUsd(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldDailyUsageUsd, v))
}

// MonthlyUsageUsd applies equality check predicate on the "monthly_usage_usd" field. It's identical to MonthlyUsageUsdEQ.
func MonthlyUsageUsd(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldMonthlyUsageUsd, v))
}

// BundleSubscriptionIDEQ applies the EQ predicate on the "bundle_subscription_id" field.
func BundleSubscriptionIDEQ(v int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldBundleSubscriptionID, v))
}

// BundleSubscriptionIDNEQ applies the NEQ predicate on the "bundle_subscription_id" field.
func BundleSubscriptionIDNEQ(v int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNEQ(FieldBundleSubscriptionID, v))
}

// BundleSubscriptionIDIn applies the In predicate on the "bundle_subscription_id" field.
func BundleSubscriptionIDIn(vs ...int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldIn(FieldBundleSubscriptionID, vs...))
}

// BundleSubscriptionIDNotIn applies the NotIn predicate on the "bundle_subscription_id" field.
func BundleSubscriptionIDNotIn(vs ...int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNotIn(FieldBundleSubscriptionID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNotIn(FieldGroupID, vs...))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldContainsFold(FieldPlatform, v))
}

// DailyLimitUsdEQ applies the EQ predicate on the "daily_limit_usd" field.
func DailyLimitUsdEQ(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldDailyLimitUsd, v))
}

// DailyLimitUsdNEQ applies the NEQ predicate on the "daily_limit_usd" field.
func DailyLimitUsdNEQ(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNEQ(FieldDailyLimitUsd, v))
}

// DailyLimitUsdIn applies the In predicate on the "daily_limit_usd" field.
func DailyLimitUsdIn(vs ...float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldIn(FieldDailyLimitUsd, vs...))
}

// DailyLimitUsdNotIn applies the NotIn predicate on the "daily_limit_usd" field.
func DailyLimitUsdNotIn(vs ...float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNotIn(FieldDailyLimitUsd, vs...))
}

// DailyLimitUsdGT applies the GT predicate on the "daily_limit_usd" field.
func DailyLimitUsdGT(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldGT(FieldDailyLimitUsd, v))
}

// DailyLimitUsdGTE applies the GTE predicate on the "daily_limit_usd" field.
func DailyLimitUsdGTE(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldGTE(FieldDailyLimitUsd, v))
}

// DailyLimitUsdLT applies the LT predicate on the "daily_limit_usd" field.
func DailyLimitUsdLT(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldLT(FieldDailyLimitUsd, v))
}

// DailyLimitUsdLTE applies the LTE predicate on the "daily_limit_usd" field.
func DailyLimitUsdLTE(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldLTE(FieldDailyLimitUsd, v))
}

// DailyLimitUsdIsNil applies the IsNil predicate on the "daily_limit_usd" field.
func DailyLimitUsdIsNil() predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldIsNull(FieldDailyLimitUsd))
}

// DailyLimitUsdNotNil applies the NotNil predicate on the "daily_limit_usd" field.
func DailyLimitUsdNotNil() predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNotNull(FieldDailyLimitUsd))
}

// MonthlyLimitUsdEQ applies the EQ predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdEQ(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdNEQ applies the NEQ predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNEQ(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNEQ(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdIn applies the In predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdIn(vs ...float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldIn(FieldMonthlyLimitUsd, vs...))
}

// MonthlyLimitUsdNotIn applies the NotIn predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNotIn(vs ...float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNotIn(FieldMonthlyLimitUsd, vs...))
}

// MonthlyLimitUsdGT applies the GT predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdGT(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldGT(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdGTE applies the GTE predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdGTE(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldGTE(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdLT applies the LT predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdLT(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldLT(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdLTE applies the LTE predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdLTE(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldLTE(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdIsNil applies the IsNil predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdIsNil() predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldIsNull(FieldMonthlyLimitUsd))
}

// MonthlyLimitUsdNotNil applies the NotNil predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNotNil() predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNotNull(FieldMonthlyLimitUsd))
}

// DailyUsageUsdEQ applies the EQ predicate on the "daily_usage_usd" field.
func DailyUsageUsdEQ(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldDailyUsageUsd, v))
}

// DailyUsageUsdNEQ applies the NEQ predicate on the "daily_usage_usd" field.
func DailyUsageUsdNEQ(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNEQ(FieldDailyUsageUsd, v))
}

// DailyUsageUsdIn applies the In predicate on the "daily_usage_usd" field.
func DailyUsageUsdIn(vs ...float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldIn(FieldDailyUsageUsd, vs...))
}

// DailyUsageUsdNotIn applies the NotIn predicate on the "daily_usage_usd" field.
func DailyUsageUsdNotIn(vs ...float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNotIn(FieldDailyUsageUsd, vs...))
}

// DailyUsageUsdGT applies the GT predicate on the "daily_usage_usd" field.
func DailyUsageUsdGT(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldGT(FieldDailyUsageUsd, v))
}

// DailyUsageUsdGTE applies the GTE predicate on the "daily_usage_usd" field.
func DailyUsageUsdGTE(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldGTE(FieldDailyUsageUsd, v))
}

// DailyUsageUsdLT applies the LT predicate on the "daily_usage_usd" field.
func DailyUsageUsdLT(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldLT(FieldDailyUsageUsd, v))
}

// DailyUsageUsdLTE applies the LTE predicate on the "daily_usage_usd" field.
func DailyUsageUsdLTE(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldLTE(FieldDailyUsageUsd, v))
}

// MonthlyUsageUsdEQ applies the EQ predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdEQ(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldEQ(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdNEQ applies the NEQ predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdNEQ(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNEQ(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdIn applies the In predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdIn(vs ...float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldIn(FieldMonthlyUsageUsd, vs...))
}

// MonthlyUsageUsdNotIn applies the NotIn predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdNotIn(vs ...float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldNotIn(FieldMonthlyUsageUsd, vs...))
}

// MonthlyUsageUsdGT applies the GT predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdGT(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldGT(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdGTE applies the GTE predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdGTE(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldGTE(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdLT applies the LT predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdLT(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldLT(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdLTE applies the LTE predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdLTE(v float64) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.FieldLTE(FieldMonthlyUsageUsd, v))
}

// HasSubscription applies the HasEdge predicate on the "subscription" edge.
func HasSubscription() predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionWith applies the HasEdge predicate on the "subscription" edge with a given conditions (other predicates).
func HasSubscriptionWith(preds ...predicate.BundleSubscription) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(func(s *sql.Selector) {
		step := newSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BundleSubscriptionEntitlement) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BundleSubscriptionEntitlement) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BundleSubscriptionEntitlement) predicate.BundleSubscriptionEntitlement {
	return predicate.BundleSubscriptionEntitlement(sql.NotPredicates(p))
}
